{
 "cells": [
  {
   "cell_type": "markdown",
   "source": [
    "### Set Parameters"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "outputs": [],
   "source": [
    "pf_id = 2 #problem formulation id; should match file name\n",
    "n_scenarios = pow(2, 10) # Ideally a power of 2 > 1000 ... 2^10 = 1024"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "### Run Model for Open Exploration"
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "##### Define a nothing policy (necessary for the code to run)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "outputs": [],
   "source": [
    "# don't @ me it has to be set up this way to work\n",
    "from ema_workbench import Policy\n",
    "policies = [Policy('policy 0', **{'0_RfR 0':0,\n",
    "                                  '0_RfR 1':0,\n",
    "                                  '0_RfR 2':0,\n",
    "                                  'A.1_DikeIncrease 0':0,\n",
    "                                  'A.1_DikeIncrease 1':0,\n",
    "                                  'A.1_DikeIncrease 2':0,\n",
    "                                  '1_RfR 0':0,\n",
    "                                  '1_RfR 1':0,\n",
    "                                  '1_RfR 2':0,\n",
    "                                  'A.2_DikeIncrease 0':0,\n",
    "                                  'A.2_DikeIncrease 1':0,\n",
    "                                  'A.2_DikeIncrease 2':0,\n",
    "                                  '2_RfR 0':0,\n",
    "                                  '2_RfR 1':0,\n",
    "                                  '2_RfR 2':0,\n",
    "                                  'A.3_DikeIncrease 0':0,\n",
    "                                  'A.3_DikeIncrease 1':0,\n",
    "                                  'A.3_DikeIncrease 2':0,\n",
    "                                  '3_RfR 0':0,\n",
    "                                  '3_RfR 1':0,\n",
    "                                  '3_RfR 2':0,\n",
    "                                  'A.4_DikeIncrease 0':0,\n",
    "                                  'A.4_DikeIncrease 1':0,\n",
    "                                  'A.4_DikeIncrease 2':0,\n",
    "                                  '4_RfR 0':0,\n",
    "                                  '4_RfR 1':0,\n",
    "                                  '4_RfR 2':0,\n",
    "                                  'A.5_DikeIncrease 0':0,\n",
    "                                  'A.5_DikeIncrease 1':0,\n",
    "                                  'A.5_DikeIncrease 2':0,\n",
    "                                  'EWS_DaysToThreat':0\n",
    "                                  })]"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "##### Import packages\n"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import numpy as np"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "##### Import things and set up model (with the selected problem formulation)\n"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "outputs": [],
   "source": [
    "from ema_workbench.util import ema_logging\n",
    "from problem_formulation import get_model_for_problem_formulation\n",
    "\n",
    "\n",
    "\n",
    "ema_logging.log_to_stderr(ema_logging.INFO)\n",
    "\n",
    "dike_model, planning_steps = get_model_for_problem_formulation(pf_id) #changes for each file"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "outputs": [
    {
     "data": {
      "text/plain": "odict_keys(['Expected Annual Damage', 'Dike Investment Costs', 'RfR Investment Costs', 'Evacuation Costs', 'Expected Number of Deaths'])"
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "(dike_model.outcomes.keys())\n",
    "#print(dike_model.levers.keys())"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "##### Define uncertainties and levers"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "outputs": [],
   "source": [
    "import copy\n",
    "uncertainties = copy.deepcopy(dike_model.uncertainties)\n",
    "levers = copy.deepcopy(dike_model.levers)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "##### Run the model with the defined number of scenarios and the nothing policy"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[MainProcess/INFO] pool started with 12 workers\n",
      "[MainProcess/INFO] performing 80 scenarios * 1 policies * 1 model(s) = 80 experiments\n",
      "  1%|▌                                          | 1/80 [00:03<05:12,  3.95s/it]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "  6%|██▋                                        | 5/80 [00:04<00:53,  1.41it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 16%|██████▊                                   | 13/80 [00:06<00:28,  2.36it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 19%|███████▉                                  | 15/80 [00:07<00:23,  2.79it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 20%|████████▍                                 | 16/80 [00:07<00:20,  3.06it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 21%|████████▉                                 | 17/80 [00:07<00:24,  2.58it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 22%|█████████▍                                | 18/80 [00:08<00:22,  2.74it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 25%|██████████▌                               | 20/80 [00:08<00:15,  3.84it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 26%|███████████                               | 21/80 [00:09<00:21,  2.69it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 31%|█████████████▏                            | 25/80 [00:10<00:19,  2.88it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 34%|██████████████▏                           | 27/80 [00:10<00:14,  3.63it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 35%|██████████████▋                           | 28/80 [00:10<00:13,  3.82it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 36%|███████████████▏                          | 29/80 [00:12<00:25,  2.01it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 38%|███████████████▊                          | 30/80 [00:12<00:24,  2.06it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 41%|█████████████████▎                        | 33/80 [00:13<00:16,  2.79it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 45%|██████████████████▉                       | 36/80 [00:13<00:10,  4.01it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 46%|███████████████████▍                      | 37/80 [00:13<00:10,  4.13it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 48%|███████████████████▉                      | 38/80 [00:15<00:23,  1.81it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 51%|█████████████████████▌                    | 41/80 [00:17<00:19,  2.00it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 52%|██████████████████████                    | 42/80 [00:17<00:17,  2.17it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 54%|██████████████████████▌                   | 43/80 [00:18<00:22,  1.68it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 55%|███████████████████████                   | 44/80 [00:18<00:18,  2.00it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 57%|████████████████████████▏                 | 46/80 [00:19<00:13,  2.48it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 65%|███████████████████████████▎              | 52/80 [00:20<00:09,  2.99it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 66%|███████████████████████████▊              | 53/80 [00:22<00:12,  2.22it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 69%|████████████████████████████▉             | 55/80 [00:22<00:10,  2.47it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 74%|██████████████████████████████▉           | 59/80 [00:23<00:05,  3.94it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 78%|████████████████████████████████▌         | 62/80 [00:23<00:03,  5.27it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 80%|█████████████████████████████████▌        | 64/80 [00:25<00:06,  2.51it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 84%|███████████████████████████████████▏      | 67/80 [00:26<00:04,  2.90it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 86%|████████████████████████████████████▏     | 69/80 [00:26<00:03,  3.36it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 88%|████████████████████████████████████▊     | 70/80 [00:26<00:03,  3.12it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 91%|██████████████████████████████████████▎   | 73/80 [00:27<00:01,  4.44it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 92%|██████████████████████████████████████▊   | 74/80 [00:27<00:01,  4.06it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 94%|███████████████████████████████████████▍  | 75/80 [00:27<00:01,  4.00it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 95%|███████████████████████████████████████▉  | 76/80 [00:27<00:01,  3.95it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 96%|████████████████████████████████████████▍ | 77/80 [00:28<00:00,  4.46it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 98%|████████████████████████████████████████▉ | 78/80 [00:28<00:00,  3.17it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      " 99%|█████████████████████████████████████████▍| 79/80 [00:28<00:00,  3.70it/s]Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "100%|██████████████████████████████████████████| 80/80 [00:28<00:00,  2.76it/s]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 244, in _store_outcomes\n",
      "    self.results[outcome][case_id,] = outcome_res\n",
      "KeyError: 'Dike Investment Costs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\ema_multiprocessing.py\", line 253, in run\n",
      "    self.callback(*result.get())\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 280, in __call__\n",
      "    self._store_outcomes(experiment.experiment_id, outcomes)\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 257, in _store_outcomes\n",
      "    self.results[outcome] = self._setup_outcomes_array(\n",
      "  File \"C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\em_framework\\callbacks.py\", line 287, in _setup_outcomes_array\n",
      "    array[:] = np.nan\n",
      "ValueError: cannot convert float NaN to integer\n",
      "[MainProcess/INFO] experiments finished\n",
      "[MainProcess/INFO] terminating pool\n"
     ]
    }
   ],
   "source": [
    "from ema_workbench import (ema_logging, MultiprocessingEvaluator, Samplers)\n",
    "ema_logging.log_to_stderr(ema_logging.INFO)\n",
    "\n",
    "with MultiprocessingEvaluator(dike_model) as evaluator:\n",
    "    results = evaluator.perform_experiments(n_scenarios, policies, uncertainty_sampling=Samplers.SOBOL)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "##### Define experiments and outcome; print names of the outcomes"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "dict_keys(['Expected Annual Damage'])\n"
     ]
    }
   ],
   "source": [
    "experiments, outcomes = results\n",
    "print(outcomes.keys())"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "### Save Results"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[MainProcess/INFO] results saved successfully to C:\\Users\\rhys_\\OneDrive - Maastricht University\\Documents\\GitHub\\MBDM\\final assignment\\output\\open_exploration\\Open_Exploration_id_2.tar.gz\n"
     ]
    }
   ],
   "source": [
    "from ema_workbench import save_results\n",
    "\n",
    "save_results(results, './output/open_exploration/Open_Exploration_id_%s.tar.gz'%pf_id)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "outputs": [],
   "source": [
    "experiments.to_csv('./output/open_exploration/Open_Exploration_id_%s_exp.csv'%pf_id, index=False)\n",
    "pd.DataFrame.from_dict(outcomes).to_csv('./output/open_exploration/Open_Exploration_id_%s_out.csv'%pf_id, index=False)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "### Visualization"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "##### Import stuff"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "outputs": [],
   "source": [
    "from ema_workbench.analysis import prim, dimensional_stacking, feature_scoring\n",
    "from ema_workbench import load_results\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import numpy as np"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "##### Load in previously saved results; can visualize without rerunning the whole notebook"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[MainProcess/INFO] results loaded successfully from C:\\Users\\rhys_\\OneDrive - Maastricht University\\Documents\\GitHub\\MBDM\\final assignment\\output\\open_exploration\\Open_Exploration_id_2.tar.gz\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "dict_keys(['Expected Annual Damage'])\n"
     ]
    }
   ],
   "source": [
    "results = load_results('./output/open_exploration/Open_Exploration_id_%s.tar.gz'%pf_id)\n",
    "experiments, outcomes = results\n",
    "print(outcomes.keys())"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "## Subspace Partitioning"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "This is where the names of each outcome will need to be fed into the visualizations to get reasonable outputs, ignore this for now or change the names yourself."
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "#### Outcome: Expected Annual Damage"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "##### Define x, y, and threshold"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "outputs": [],
   "source": [
    "x = experiments\n",
    "data = outcomes[\"Expected Annual Damage\"]\n",
    "y = data < np.percentile(data, 10) #np.quantile(data, .5)\n",
    "#data <  np.percentile(data, 10) # not sure how this work, gives better density coverage results?\n",
    "#quantile"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "##### Tradeoff density and coverage"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[MainProcess/INFO] policy dropped from analysis because only a single category\n",
      "[MainProcess/INFO] model dropped from analysis because only a single category\n",
      "[MainProcess/INFO] 80 points remaining, containing 3 cases of interest\n",
      "[MainProcess/INFO] box does not meet threshold criteria, value is 0.25, returning dump box\n"
     ]
    },
    {
     "data": {
      "text/plain": "<Figure size 432x288 with 2 Axes>",
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAUMAAAEKCAYAAACIZDejAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjQuMywgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/MnkTPAAAACXBIWXMAAAsTAAALEwEAmpwYAAAZaUlEQVR4nO3de5xcdZ3m8c9jCCxguAeHCURCDITogAstIMQRcNCEQbOgoyCIRDALclF0XRh2VlGWlyArC14wZiCAOALjgBCZAMsiFyEgJAghAXGyRKEFhyAaIiDY4Zk/zmmotN1dpzs5XZ3q5/161avqXH7nfGkrj786t59sExEx0r2h1QVERAwHCcOICBKGERFAwjAiAkgYRkQACcOICKDGMJQ0V9Izkpb0sfxISYvL1wJJu9dVS0REM3X2DC8DpvWzfDnwbtu7AWcBc2qsJSKiXxvUtWHbd0rasZ/lCxom7wW2r6uWiIhmagvDAToWuLGvhZJmAbMANt100z0nT548VHVFjEiLFi161vbYwbaX5A13qNa/eeXJTmxrsPtaV1oehpIOoAjDqX2tY3sO5c/ojo4OL1y4cIiqixiZJP1qbbcx7nOnVlpv+Wc+t7a7WidaGoaSdgMuBqbb/m0ra4mIka1ll9ZIGg9cC3zM9i9aVUdEBNTYM5R0JbA/sI2kTuCLwGgA27OBLwBbAxdJAuiy3VFXPRER/anzbPIRTZYfBxxX1/4jIgYid6BERJAwjIgAEoYREUDCMCICSBhGRAAJw4gIIGEYEQEkDCMigIRhRASQMIyIABKGERFAwjAiAkgYRkQACcOICCBhGBEBJAwjIoCEYUQEkDCMiAAShhERQMIwIgJIGEZEAAnDiAggYRgRASQMIyKAhGFEBJAwjIgAEoYREUCNYShprqRnJC3pY7kkfV3SMkmLJe1RVy0REc3U2TO8DJjWz/LpwKTyNQv4do21RET0q7YwtH0n8Fw/q8wAvuvCvcAWkrarq56IiP608pjhOODJhunOcl5ExJBrZRiql3nudUVplqSFkhauWLGi5rIiYiRqZRh2Ajs0TG8PPNXbirbn2O6w3TF27NghKS4iRpZWhuE84OjyrPI+wErbT7ewnogYwTaoa8OSrgT2B7aR1Al8ERgNYHs2MB84GFgGvAjMrKuWiIhmagtD20c0WW7gxLr2HxExELkDJSLahqSJkjYqP+8v6RRJW1RpmzCMiHZyDbBa0luAS4AJwPerNEwYRkQ7edV2F3AocIHtU4FKN3MkDCOinfxJ0hHAx4EbynmjqzRMGEZEO5kJvBM42/ZySROA71VpWNvZ5IiIoWb7EeCUhunlwDlV2iYMI6JtSNoPOBN4M0W+ieJKvp2atU0YRkQ7uQQ4FVgErB5Iw4RhRLSTlbZvHEzDhGFEtJPbJJ0HXAu83D3T9gPNGiYMI6Kd7F2+dzTMM3Bgs4YJw4hoG7YPGGzbXGcYEW1D0uaSzu9+GLSkr0navErbhGFEtJO5wCrgw+XreeDSKg3zMzki2slE2x9smP6SpAerNEzPMCLayUuSpnZPlBdhv1SlYXqGEdFOTgAuL48TimK44mOqNEwYRkTbsP0gsLukzcrp56u2TRhGxHpP0lG2vyfpsz3mA2D7/GbbSBhGRDvYtHwfM9gNJAwjYr1n+zvl+5cGu42cTY6ItiHpq5I2kzRa0q2SnpV0VJW2CcOIaCfvLU+aHAJ0AjsDn6/SMGEYEe2ke7yTg4ErbT9XtWGOGUZEO/mRpJ9TXGj9KUljgT9WaZieYUS0DdunUwwI1WH7T8ALwIwqbdMzjIh2syuwo6TGfPtus0YJw4hoG5KuACYCD/L6GCim1WEoaRpwITAKuNj2OT2Wb04xpun4spb/bbvS43YiInrRAUyx7YE2rO2YoaRRwLeA6cAU4AhJU3qsdiLwiO3dgf2Br0nasK6aIqLtLQH+YjAN6+wZ7gUss/04gKSrKA5kPtKwjoExKm4gfCPFEya6aqwpItrbNsAjku5jzQGhPtCsYZ1hOA54smG6k9cHa+n2TWAe8BTFPYUfsf1qzw1JmgXMAhg/fnwtxUZEWzhzsA3rvLRGvczr+Tv+fRQHOv8SeDvwze5H76zRyJ5ju8N2x9ixY9d1nRHRJmzfAfwSGF1+vh9oOkwo1BuGncAODdPbU/QAG80ErnVhGbAcmFxjTRHRxiR9EvgX4DvlrHHAdVXa1hmG9wOTJE0oT4ocTvGTuNETwHsAJL0J2AV4vMaaIqK9nQjsRzEQFLb/Ddi2SsPajhna7pJ0EnAzxaU1c20vlXR8uXw2cBZwmaSHKX5Wn2b72bpqioi297LtV7of6lpeeF3pMptarzO0PR+Y32Pe7IbPTwHvrbOGiBhR7pB0BrCxpIOATwE/qtIw9yZHRDs5HVgBPAz8V4rO2D9UaZjb8SKibZSX5v1j+RqQ9Awjom1IOkTSzyQ9J+l5SaskVRohLz3DiGgnFwCHAQ8P9P7k9Awjop08CSwZzIMa0jOMiHby34H5ku5gzXuTM25yRIwoZwN/AP4TMKAnYCUMI6KdbGV7UNcu55hhRLST/ycpYRgRI96JwE2SXsqlNRExYtkeM9i2CcOIWO9Jmmz755L26G257abPNEwYRkQ7+BzwSeBrvSwzcGCzDSQMI2K9Z/uT5fsBg91GpTCUdAgwv7fxSSIiWk3SYf0tt31ts21U7RkeDlwo6RrgUtuPVmwXETEU3l++bwvsC/y4nD4AuB1YN2Fo+6hyoKYjgEslGbgUuNL2qgEWHRGxTtmeCSDpBopB5J8up7ejGL+9qcrXGdp+HrgGuArYDjgUeEDSyQOsOyKiLjt2B2Hp34GdqzSseszwAxQj2U0ErgD2sv2MpE2AR4FvDKzeiIha3C7pZuBKirPIhwO3VWlY9Zjhh4D/Y/vOxpm2X5T0iYFUGhFRF9snSToU+Oty1hzbP6zStmoYPt0zCCWda/s027cOoNaIiFqV4VcpABtVPWZ4UC/zpg90ZxERw1W/PUNJJ1AMtTdR0uKGRWOAu+ssLCJiKDX7mfx94EbgKxRD8HVbZfu52qqKiBhizcLQtn8p6cSeCyRtlUCMiOFA0sMUZ497ZXu3Ztuo0jM8BFhU7kiN2wd2al5mRETtDinfuztuV5TvRwIvVtlAv2Fo+5DyfcJgqouIGAq2fwUgaT/b+zUsOl3S3cCXm22j0tlkSftJ2rT8fJSk8yWNr9BumqTHJC2TdHof6+wv6UFJS8sRrSIi1lAlS0qbSpra0G5fYNMq+6h6neG3gd0l7U4xFN8lFN3Qd/fVQNIoinsCDwI6gfslzbP9SMM6WwAXAdNsPyFp24r1RMQIUSVLGhwLzJW0OcWhvJVApRtDqoZhl21LmgFcaPsSSR9v0mYvYJntxwEkXQXMABr/Az4KXGv7CQDbz1SsJyJGjipZAoDtRRQdt80A2V5ZdSdVL7peJenvgaOAfy2TenSTNuMoRrfv1lnOa7QzsKWk2yUtknR0bxuSNEvSQkkLV6xYUbHkiFhfdP/7Ll+zeiyukiXd23mTpEuAq22vlDRF0rFVaqgahh+hGJ3+WNu/KQs5r0kb9TKv56nvDYA9gb8F3gf8T0l/9oQJ23Nsd9juGDt2bMWSI2J90f3vu3zN6bG4SpZ0uwy4GfjLcvoXwGeq1FApDG3/xvb5tn9STj9h+7tNmnUCOzRMbw881cs6N9l+wfazwJ3A7lVqiogRo0qWdNvG9j8DrwLY7gJWV9lJ1bPJh0n6N0krBzAW6f3AJEkTJG1I8SideT3WuR54l6QNyseB7U3xSLCIiG5VsqTbC5K2puw5StqH4iRKU1VPoHwVeP9AHvdvu0vSSRRd1lHAXNtLJR1fLp9t+1FJNwGLKZL8YttLqu4jItpfX1nSx+qfpQjKieX1hWOBv6uyn6ph+O+DGffE9nxgfo95s3tMn0fz448RMYL1liV9WEpxyd8uFMcaH6PiL+CqYbhQ0tXAdRQnUroLbDrISkTEELrH9h4UoQiApAeAXgeXb1Q1DDejuL/vvQ3zTIURpyIi6ibpLyiuctlY0n/m9TPQmwGbVNlG1dHxZg6qwoiIofE+4BiKM83nN8x/HjijygaqDgi1M8UteW+y/TZJuwEfsP2/BlRuREQNbF8OXC7pg7avGcw2ql50/Y/A3wN/Kne8mOL0dkTEcLJn+cwDACRtKalSp61qGG5i+74e87oqto2IGCrTbf++e8L274CDqzSsGobPSprI6xcyfgh4uv8mERFDbpSkjbonJG0MbNTP+q+pejb5RGAOMFnSr4HlFE+QjYgYTr4H3CrpUorO2yeAy6s0bDY63mcbJudTjEz/BuAF4IOsedYmIqKlbH+1HA/lPRSX15xl++YqbZv1DMeU77sA76C4l1jAxygeqhARMazYvpFiVM8BaTYGypcAJP1fYA/bq8rpM4EfDLzMiIh1T9JdtqdKWsWaj/cSxSifmzXbRtVjhuOBVxqmXwF2rFpoRESdbE8t38c0W7cvVcPwCuA+ST+kSN1DqXhQMiJiKEh6A7DY9tsG077q7XhnS7oReFc5a6btnw1mhxERdbD9qqSHJI3vHldpIKr2DLH9APDAQHcQETGEtgOWSrqP4qoXAGx/oFnDymEYEbEe+NJgGyYMI6KdHGz7tMYZks4F7mjWsOrteBER64ODepk3vUrD9AwjYr0n6QTgUxRjnyxuWDQGuLvKNhKGEdEOvk9x18lXgNMb5q+y/VyVDeRnckSs92yvtP1L4B+A39j+FTABOKrx+Yb9SRhGRDu5Blgt6S3AJRSB+P0qDROGEdFOXrXdBRwGXGD7VIprD5tKGEZEO/mTpCOAo4EbynmjqzRMGEZEO5kJvBM42/ZySRMoHvjaVM4mR0TbsP2IpNMonrSF7eXAOVXapmcYEW1D0vuBB4Gbyum3S5pXpW2tYShpmqTHJC2TdHo/671D0upyoKmIiME6E9gL+D2A7Qcpzig3VVsYShoFfIviVpgpwBGSpvSx3rlApXEKIiL60WV7ZY957nXNHursGe4FLLP9uO1XgKuAGb2sdzLFtUHP1FhLRIwMSyR9lGLI0EmSvgEsqNKwzjAcBzzZMN1ZznuNpHEUT82e3d+GJM2StFDSwhUrVqzzQiOibZwMvBV4meJi65XAZ6o0rPNssnqZ17O7egFwmu3VUm+rl43sORTjNtPR0VGpyxsRI0t5yG2e7b8B/sdA29cZhp3ADg3T2wNP9VinA7iqDMJtgIMlddm+rsa6IqINlZ2qFyVt3stxw6bqDMP7gUnlRY+/Bg4HPtq4gu3XzvJIugy4IUEYEWvhj8DDkm5hzcf+n9KsYW1haLtL0kkUZ4lHAXNtL5V0fLm83+OEERGD8K/la8BqvQPF9nxgfo95vYag7WPqrCUi2p/tQQ9hnDtQIiJIGEZEAAnDiGgDkq4o3z892G0kDCOiHewp6c3AJyRtKWmrxleVDeQRXhHRDmZTPKlmJ2ARa9704XJ+v9IzjIj1nu2v296V4hK+nWxPaHg1DUJIzzAi2ojtEyTtDryrnHWn7cX9temWnmFEtA1JpwD/BGxbvv5J0slV2qZnGBHt5Dhgb9svAEg6F7gH+EazhukZRkQ7EbC6YXo1vT9B68+kZxgR7eRS4KeSflhO/xeKweSbShhGRNuwfb6k24GpFD3CmbZ/VqVtwjAi2ortB4AHBtouxwwjIkgYRkQACcOICCBhGBFtTtKcKuslDCOiLUgaJenUXhZ9p0r7hGFEtAXbq4EZvcxfVKV9Lq2JiHZyt6RvAlez5uh4TS+1SRhGRDvZt3z/csM8Awc2a5gwjIi2YfuAwbZNGEZE25C0EfBBYEca8s32l/tq0y1hGBHt5HpgJcWj/18eSMOEYUS0k+1tTxtMw1xaExHtZIGkvxpMw/QMI6KdTAWOkbSc4meyANverVnDWsNQ0jTgQmAUcLHtc3osPxI4rZz8A3CC7YfqrCki2tr0wTasLQwljQK+BRwEdAL3S5pn+5GG1ZYD77b9O0nTgTnA3nXVFBHtzfavBtu2zmOGewHLbD9u+xXgKnrcKmN7ge3flZP3AtvXWE9ERJ/qDMNxwJMN053lvL4cC9xYYz0REX2q85hhbyNSudcVpQMownBqH8tnAbMAxo8fv67qi4h4TZ09w05gh4bp7YGneq4kaTfgYmCG7d/2tiHbc2x32O4YO3ZsLcVGxMhWZxjeD0ySNEHShsDhwLzGFSSNB64FPmb7FzXWEhHRr9p+JtvuknQScDPFpTVzbS+VdHy5fDbwBWBr4CJJAF22O+qqKSKiL7VeZ2h7PjC/x7zZDZ+PA46rs4aIiCpyO15EBAnDiAggYRgRASQMIyKAhGFEBJAwjIgAEoYREUDCMCICSBhGRAAJw4gIIGEYEQEkDCMigIRhRASQMIyIABKGERFAwjAiAkgYRkQACcOICCBhGBEBJAwjIoCEYUQEUPPoeBHRt+t//ijnLbiLp1etYrsxY/j8vlOZMXnXVpc1YiUMI1rg+p8/yhm33sJLXV0APLVqFWfcegtAArFF8jM5ogXOW3DXa0HY7aWuLs5bcFeLKoqEYUQLPL1q1YDmR/0ShhEtsN2YMQOaH/VLGEa0wOf3ncrGG6x5yH7jDTbg8/tObVFFkRMoES3QfZIkZ5OHj1rDUNI04EJgFHCx7XN6LFe5/GDgReAY2w/UWVPEcDFj8q4Jv2Gktp/JkkYB3wKmA1OAIyRN6bHadGBS+ZoFfLuueiIi+lPnMcO9gGW2H7f9CnAVMKPHOjOA77pwL7CFpO1qrCkiold1/kweBzzZMN0J7F1hnXHA040rSZpF0XMEeFnSknVb6lrZBni21UX0MNxqSj39G271AOyythtY/pnPLaq46p5ru691oc4wVC/zPIh1sD0HmAMgaaHtjrUvb90YbvXA8Ksp9fRvuNUDRU1r0952b/+2h7U6fyZ3Ajs0TG8PPDWIdSIialdnGN4PTJI0QdKGwOHAvB7rzAOOVmEfYKXtp3tuKCKibrX9TLbdJekk4GaKS2vm2l4q6fhy+WxgPsVlNcsoLq2ZWWHTc2oqebCGWz0w/GpKPf0bbvXA8KypVrL/7BBdRMSIk9vxIiJIGEZEAMM4DCVNk/SYpGWSTu9luSR9vVy+WNIeLa7nyLKOxZIWSNq9lfU0rPcOSaslfajOeqrWJGl/SQ9KWirpjlbWI2lzST+S9FBZT5Vj1mtTz1xJz/R1nWwLvtPN6hnS73TL2R52L4oTLv8f2AnYEHgImNJjnYOBGymuVdwH+GmL69kX2LL8PL3V9TSs92OKE1UfGgb/m20BPAKML6e3bXE9ZwDnlp/HAs8BG9ZY018DewBL+lg+ZN/pivUM2Xd6OLyGa89wuN3K17Qe2wts/66cvJfimsm6VPn7AJwMXAM8U2MtA6npo8C1tp8AsF1nXVXqMTCmfGDIGynCsIua2L6z3EdfhvT21Gb1DPF3uuWGaxj2dZveQNcZynoaHUvx//B1aVqPpHHAocDsGusYUE3AzsCWkm6XtEjS0S2u55vArhQX+j8MfNr2qzXW1MxQfqcHqu7vdMsN1+cZrrNb+daRyvuSdADFF6fOp3RWqecC4DTbq4uOT+2q1LQBxX2o7wE2Bu6RdK/tX7SonvcBDwIHAhOBWyT9xPbzNdRTxVB+pysbou90yw3XMBxut/JV2pek3YCLgem2f1tTLVXr6QCuKoNwG+BgSV22r2thTZ3As7ZfAF6QdCewO1BHGFapZyZwjouDYsskLQcmA/fVUE8Vw+721CH8Trdeqw9a9vaiCOnHgQm8fvD7rT3W+VvWPNh8X4vrGU9xJ82+w+Hv02P9y6j/BEqVv9GuwK3lupsAS4C3tbCebwNnlp/fBPwa2Kbmv9OO9H3CYsi+0xXrGbLv9HB4Dcueoeu7la/Oer4AbA1cVPbGulzTk0gq1jOkqtRk+1FJNwGLgVcpnn5ey+PYKv6NzgIuk/QwRQCdZru2R2lJuhLYH9hGUifwRWB0Qz1D9p2uWM+QfaeHg9yOFxHB8D2bHBExpBKGEREkDCMigIRhRASQMIyIABKGERFAwjCGmKRheW1rRMIwXiPp6PLZdQ9JukLSmyXdWs67VdL48hmAv5T0hrLNJpKelDRa0kRJN5UPYfiJpMnlOpdJOl/SbcC5kvYqn4/3s/J9l4Zt/XO5v6sl/VRSR7nsvZLukfSApB9IemPL/lDRnlp9C0xew+MFvBV4jPJ2NGAr4EfAx8vpTwDXlZ+vBw4oP3+E4k4SKG61m1R+3hv4cfn5MuAGYFQ5vRmwQfn5b4Brys//DfhO+fltFI/T6qC4t/pOYNNy2WnAF1r9N8urvV75yRLdDgT+xeXtaLafk/RO4LBy+RXAV8vPV1OE4G0UQ8BeVPbU9gV+0PCUnI0atv8D26vLz5sDl0uaRPFUltHl/KnAheX+l0haXM7fB5gC3F1ue0PgnnXxHx3RLWEY3UTzx0V1L58HfEXSVhSP5PoxsCnwe9tv76PtCw2fzwJus32opB2B2xtq6Ku2W2wf0aS+iEHLMcPodivwYUlbA5RBt4Ci5wdwJHAXgO0/UDzm6kLgBturXTwDcLmkvyvbq58xMzaneEIMwDEN8+8CPly2nwL8VTn/XmA/SW8pl20iaee1+8+NWFPCMACwvRQ4G7hD0kPA+cApwMzy5+rHgE83NLkaOKp873YkcGzZfim9D0UAxc/tr0i6m+KJMt0uAsaW+zuN4uk2K22voAjNK8tl91I8dzBinclTa2LYkDQKGG37j5ImUvRWd3YxhklErXLMMIaTTYDbJI2mOE54QoIwhkp6hhER5JhhRASQMIyIABKGERFAwjAiAkgYRkQA8B/gKcqNpCJ+BgAAAABJRU5ErkJggg==\n"
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "prim_alg = prim.Prim(x, y, threshold=0.8)\n",
    "box1 = prim_alg.find_box()\n",
    "box1.show_tradeoff()\n",
    "plt.show()"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\rhys_\\anaconda3\\lib\\site-packages\\ema_workbench\\analysis\\scenario_discovery_util.py:456: UserWarning: Attempting to set identical bottom == top == -0.5 results in singular transformations; automatically expanding.\n",
      "  ax.set_ylim(top=-0.5, bottom=nr_unc - 0.5)\n"
     ]
    },
    {
     "data": {
      "text/plain": "<Figure size 432x288 with 1 Axes>",
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAX4AAAD4CAYAAADrRI2NAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjQuMywgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/MnkTPAAAACXBIWXMAAAsTAAALEwEAmpwYAAAMZUlEQVR4nO3db2xV9R3H8c+XUbiuGW1ZKUVW7EjgASj4B83GFlJQI3QYIdmDLksqCxEhTtSQmRGSrmpiTAhP9oASsqDwYAzthJiJAxJUzFSWQqoUwxSoDGKgK7SAcGvT9rcHvWCtUM6F9tx7+32/khvbc89pfz8P993DuacHCyEIAODHiEwPAAAQL8IPAM4QfgBwhvADgDOEHwCcGZnOysXFxaG8vHyIhnLrurq6ZGaZHgaQlUIIGjkyrZd87A4cONAaQhg32F/3tttuO93R0TF+sL9uuhKJRE9HR0dsB9yJROJMMpks7b88rT8F5eXlamhoGLxRDbKWlhaNGjUq08MAslJnZ6dKSkoyPYwBmdmJofi6HR0d47Ph0nUzGxHnOMzsmj/sONUDAM4QfgBwhvADQI77/PPPtWTJEu3YsSPS+tn9Tg8ADIEPPvhA7777rsaNG6cjR45o0qRJmjBhgk6ePKnHH39cjY2N6unpUVNTk0aMGKGzZ8/qySef1DPPPKMnnnhCBQUFOnjwoE6ePKm1a9fqueee07Rp0/T222/r9ddf1+rVq1VaWqrCwkItW7ZsyOczdepULVmyRO3t7ZHW54gfgDvbt29XTU2N7rvvPt11111atWqV3n//fVVXV2vz5s3atWuX5s+fr927d6u4uFhdXV3q7OzU7NmztXDhQl24cEH5+fk6fPiwWlpaNGbMGC1btkwFBQU6dOiQ2traVFJSotbW1kxP9Zo44gfgzuLFi/Xiiy+qqKhIR48e1bp161RRUXH1qL+8vFwjRozQQw89pHPnzmnq1KkaNWqURo8eLUlqampSWVmZuru7VVJSovPnz2vjxo26ePGi7rzzThUUFOjixYuaOXNmLPM5ffq06uvrlUwmdc899+iOO+4YcH1L59KiWbNmBS7nBHJTjlzOeSCEMGsIvm4Yyssod+7cqebmZknSU089NdA4FPPlnAohfO+XmzjiB4BbVFlZmekhpIVz/ADgDEf8AIa9RCLRY2YZP9BNJBKx3lYmkUj0XGs54Qcw7HV0dMR6q4TrycA5/mv+sMv4T0AAQLwIPwA4w6keAG699957am9v16JFiyKtv23bNo0fPz6tbQZy8OBBvfnmm7p8+bJeeukl5efna/PmzWptbdWlS5dUU1Oj+vp6HT9+XN98842ef/551dXV6dKlSzp27Jg2bdqkBQsW6JFHHtHDDz+s6dOnR/q+HPEDcGfPnj2qra3VG2+8oZ6eHr388stauXKl2traVFlZqS1btmj16tU6ceKEnn76adXV1amjo0MfffSRvvjiC+3du1efffaZ1qxZI0lauXLlTY1j69atqq2t1aJFi7Rnzx5JUmNjo1atWiVJam9v14MPPqhz586pu7tbo0eP1rPPPqvi4mKtWLFCklRaWqrW1ta0/q0Fwg/Anbfeektr1qzRvHnzVF1drdtvv10TJ05Uc3OzJk+erOrqaiWTSZWUlKisrExnz569+qbslClTNG/ePE2bNk1jxozRtm3bNHfu3Jsey5WrfPpf7XPl86KiIr3yyitXf2tYkhoaGnT//fdLkl599VW98MILWr9+feTvyakeAO4sXLhQdXV1am5u1muvvaYjR45o7NixmjRp0neOnM+cOaP8/HydOnXq6n13ysrKVF9frylTpmjp0qVasGCB9u/ff1PjqKqqUm1trS5fvqwZM2bo9OnTuvvuu7Vu3TpJUmFhodauXavu7m4lk0lJ0r59+zRnzhxJUltbmzZs2KALFy6ooqIi8vfllg2AE9yyYfAvo9ywYYMKCwtVVVUVdRzcsgEActny5cszPYSbwjl+AHCGI34Aw14ikThzvX94POZxxHrriEQiceZaywk/gGEvmUyWZnoM2YRTPQDgDOEHAGcIPwA4Q/gBwBnCDwDOEH4AcIbwA4AzhB8AnCH8AOAM4QcAZwg/ADhD+AHAGcIPAM4QfgBwhvADgDOEHwCcIfwA4AzhBwBnCD8AOEP4AcAZwg8AzhB+AHCG8AOAM4QfAJwh/ADgDOEHAGcIPwA4Q/gBwBnCDwDOEH4AcIbwA4AzhB8AnCH8AOAM4QcAZwg/ADhD+AHAGcIPAM4QfgBwhvADgDOEHwCcIfwA4AzhBwBnCD8AOEP4AcAZwg8AzhB+AHCG8AOAM4QfAJwh/ADgDOEHAGcIPwA4Q/gBwBnCDwDOEH4AcIbwA4AzhB8AnCH8AOAM4QcAZwg/ADhD+AHAGcIPAM4QfgBwhvADgDOEHwCcIfwA4AzhBwBnCD8AOEP4AcAZwg8AzhB+AHCG8AOAM4QfAJwh/ADgDOEHAGcIPwA4Q/gBwBnCDwDOEH4AcIbwA4AzhB8AnCH8AOAM4QcAZwg/ADhD+AHAGcIPAM6MzPQABlNeXp46OzszPQwgK+Xl5WV6CMgSwyr8RUVFmR4CAGQ9TvUAgDOEHwCcIfwA4AzhBwBnCD8AOEP4AcAZwg8AzhB+AHCG8AOAM4QfAJwh/ADgDOEHAGcIPwA4Q/gBwBnCDwDOEH4AcIbwA4AzhB8AnCH8AOAM4QcAZwg/ADhD+AHAGcIPAM4QfgBwhvADgDOEHwCcIfwA4AzhBwBnCD8AOEP4AcAZwg8AzhB+AHCG8AOAM4QfAJwh/ADgDOEHAGcIPwA4Q/gBwBnCDwDOEH4AcIbwA4AzhB8AnCH8AOAM4QcAZwg/ADhD+AHAGcIPAM4QfgBwhvADgDOEHwCcIfwA4AzhBwBnCD8AOEP4AcAZwg8AzhB+AHCG8AOAM4QfAJwh/ADgDOEHAGcIPwA4Q/gBwBnCDwDOEH4AcIbwA4AzhB8AnCH8AOAM4QcAZwg/ADhD+AHAGcIPAM4QfgBwhvADgDOEHwCcIfwA4AzhBwBnCD8AOEP4AcAZwg8AzhB+AHCG8AOAM4QfAJwh/ADgDOEHAGcIPwA4Q/gBwBnCDwDOEH4AcIbwA4AzhB8AnCH8AOAM4QcAZwg/ADhD+AHAGcIPAM4QfgBwhvADgDOEHwCcIfwA4AzhBwBnCD8AOEP4AcAZwg8AzhB+AHCG8AOAM4QfAJwh/ADgjIUQoq9s9j9JJ4ZuOLesWFJrpgcxCJhHdmEe8bkjhDAu04MY7tIKf7Yzs4YQwqxMj+NWMY/swjww3HCqBwCcIfwA4MxwC//GTA9gkDCP7MI8MKwMq3P8AIAbG25H/ACAGyD8AOBMToTfzOab2X/M7KiZ/fEaz5uZ/Tn1/Kdmdm/UbeMUYR6/TY3/UzP70Mxm9nnuSzM7ZGaNZtYQ78i/L8JcKszsfGq8jWZWE3XbOEWYxx/6zKHJzLrNbGzquazYJ2a2ycxazKzpOs/nxOsDMQohZPVD0g8kHZM0WdIoSZ9ImtZvnUpJ70gyST+TtD/qtlk2j9mSilIfL7gyj9TnX0oqzvT+SGMuFZL+cTPbZtM8+q3/qKS92bZPJM2RdK+kpus8n/WvDx7xPnLhiP8BSUdDCMdDCJ2S/ibpsX7rPCZpS+j1saRCM5sQcdu43HAsIYQPQwhtqU8/lvSTmMcY1a38f82pfdLPbyRtjWVkaQgh7JN0boBVcuH1gRjlQvgnSjrZ5/NTqWVR1omybVzSHctS9R6lXREk7TazA2a2bAjGl46oc/m5mX1iZu+Y2fQ0t41D5LGY2Q8lzZf09z6Ls2mfDCQXXh+I0chMDyACu8ay/tegXm+dKNvGJfJYzGyuesP/yz6LfxFC+MrMSiTtMbMjqSO9TIgyl4Pqve/K12ZWKWmHpCkRt41LOmN5VNK/Qgh9j6yzaZ8MJBdeH4hRLhzxn5JU1ufzn0j6KuI6UbaNS6SxmNkMSX+R9FgI4eyV5SGEr1L/bZG0Xb1/Tc+UG84lhHAhhPB16uOdkvLMrDjKtjFKZyxV6neaJ8v2yUBy4fWBOGX6TYYbPdT7t5Ljkn6qb9+Amt5vnV/pu29e/Tvqtlk2j0mSjkqa3W95vqQf9fn4Q0nzs3yflOrbXxB8QNJ/U/snp/ZJar0C9Z5Dz8/ifVKu67+5m/WvDx7xPrL+VE8IocvMfi9pl3qvQtgUQjhsZstTz2+QtFO9Vy4clXRZ0u8G2jYD04g6jxpJP5a03swkqSv03k1xvKTtqWUjJf01hPDPDExDqbFGmcuvJa0wsy5JSUlVIYQgKdf2iSQtlrQ7hHCpz+ZZs0/MbKt6r6IqNrNTkv4kKU/KndcH4sUtGwDAmVw4xw8AGESEHwCcIfwA4AzhBwBnCD8AOEP4AcAZwg8AzvwfcnL+0EmlLOQAAAAASUVORK5CYII=\n"
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "box1.inspect(style='graph')\n",
    "plt.show()"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "##### Dimensional stacking"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[MainProcess/INFO] policy dropped from analysis because only a single category\n",
      "[MainProcess/INFO] model dropped from analysis because only a single category\n"
     ]
    },
    {
     "data": {
      "text/plain": "<Figure size 720x720 with 4 Axes>",
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAo4AAAKzCAYAAACQ6oyTAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjQuMywgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/MnkTPAAAACXBIWXMAAAsTAAALEwEAmpwYAABN0klEQVR4nO3de1xVdaL+8WcD0ijktYCmyAYvx4lMpyBHK0kKMS5h4P2SYzndTOowM4Yymtr1VMfmTJnlsUybOY6jmaiolVrq5C0xh2ORlj9NKdlEWggkl836/cFxTwTCUvdmLdif9+vl67hvaz3fgW3P+a61vsthGIYhAAAAoAl+VgcAAABAy0BxBAAAgCkURwAAAJhCcQQAAIApFEcAAACYQnEEAACAKbYsjtOmTVP//v2VlJTU4OuGYeiJJ55QXFyckpOT9cknn7hf27p1q+Lj4xUXF6cFCxY0V2QAAIBWz5bFMTU1VQsXLjzr61u3btWRI0f07rvv6vHHH9esWbMkSS6XS3PmzNHChQuVk5OjtWvX6osvvmim1AAAAK2bLYtjdHS0OnTocNbXN23apKFDh8rhcKhv374qKSlRUVGR8vLy1LVrV4WHhyswMFCJiYnatGlTMyYHAABovWxZHJvidDoVFhbmfhwWFian01nv+dDQUDmdTisiAgAAtDoBjb1YcTzCKztdtfVpLVu2zP145MiRGjlypOnPN3SXRIfDcdbnAQAAcOEaL45GtVd2eq5F8afCwsJUWFjoflxYWKiQkBBVVVXVed7pdCokJOSCsrYW/fv3144dO6yOAfiM2bNn67HHHrM6BuBTUlNTtXLlSqtjtGqNHqqukMsrfy5UbGysVq1aJcMwtG/fPl188cUKCQlR7969deTIER07dkyVlZXKyclRbGzsBe8PAAAATcw4njZqmitHHRkZGdq9e7dOnjypgQMHasqUKaqurp39HD16tGJiYrRlyxbFxcWpbdu2euqppyRJAQEBmjlzpiZNmiSXy6W0tDT16NHDkjEAAAC0Nk0UR2vOD5w7d26jrzscjrMeAoqJiVFMTIw3YgEAAPi0Jopji7zoGgAAAF7QRHFs9GUAAAD4kMaLYw3FEQAAALWamHFs01w5AAAAYHMURwAAAJhCcQQAAIApTZzjSHEEAABArSZuOUhxBAAAQC1mHAGbmjZtmj744AN16dJFa9eutToO0OodP35cU6dOVXFxsfz8/DRixAhNmDDB6liArXCOI2BTqampGjdunB599FGrowA+wd/fX5mZmYqMjFRpaanS0tJ04403qnv37lZHA2yj8UPVzDgClomOjlZBQYHVMQCfERISopCQEElScHCwIiIi5HQ6KY6tzHvvvaeHHnpI69atU7du3eq8VlFRobFjx6qyslIul0vx8fFKT08/67YyMzO1e/duXXzxxaqoqFBSUpIeeuihc8qzceNGXXXVVS3m96zRewqermnjlT8AANhZQUGB8vPz1adPH6ujwMPWrl2r66+/XuvWrav3WmBgoBYvXqzVq1dr1apV2rZtm/bt29fo9qZOnars7GxlZ2fr7bff1rFjx+q9x+VynfXzGzdu1BdffHHO47BKEzOO3DkGAOBbysrKlJ6erunTpys4ONjqOPCgsrIy7d27V0uWLNEDDzygKVOm1Hnd4XAoKChIklRdXa3q6mo5HA5T266oqJAktWvXTpIUGxur1NRUffjhhxo3bpzKysq0bNkyVVVVqWvXrnr22WeVn5+vzZs3a/fu3Zo/f75efPFFSdLs2bN18uRJ/exnP9Pjjz9eb2bUSrYtjlu3btWTTz6pmpoaDR8+XPfee2+d1xcuXKg1a9ZIqm3yhw4d0o4dO9SxY0fFxsYqKChIfn5+8vf318qVK60YAgCghamqqlJ6erqSk5M1ePBgq+PgHJ08eVKpqanuxyNHjtTIkSPdjzdu3Kibb75Zv/jFL9SxY0d98sknioyMrLMNl8ul1NRUHT16VGPGjGly1vnZZ5/V/PnzdfToUY0fP15dunRxv3bRRRdp6dKl7mwjRoyQJL3wwgtasWKFxo8fr9jYWN1yyy0aMmSIJGnChAmaPXu2rrrqKv3zn//U7NmztWTJkgv7H8aDbFkcXS6X5syZo0WLFik0NFTDhg1TbGxsneP/kyZN0qRJkyRJmzdv1htvvKGOHTu6X1+8eLE6d+7c3NEBAC2UYRjKyspSRESEJk6caHUcnIdOnTo1OlmUk5PjvlI+ISFBa9eurVcc/f39lZ2drZKSEk2ePFkHDx5Uz549z7rNqVOnasiQISorK9NvfvMb7d27V9ddd517H2d8/vnn+tOf/qRTp06prKxMN910U71tlZWV6eOPP9bDDz/sfq6ystLc4JuJLYtjXl6eunbtqvDwcElSYmKiNm3adNYTR3NycpSUlNScEQGvy8jI0O7du3Xy5EkNHDhQU6ZM0fDhw62OBbRaubm5ys7OVs+ePZWSkiKp9nsYExNjcTJ4wsmTJ7Vz5059/vnncjgccrlccjgcmjp1aoOHo9u3b69+/fpp27ZtjRbHM4KCgnTDDTcoNzfXXRzbtm3rfj0zM1Mvv/yyevXqpZUrV2r37t31tmEYhtq3b6/s7OwLGKl3NdoMq2v8vbLTZcuWadmyZe7HP51KdjqdCgsLcz8ODQ1VXl5eg9v64YcftG3bNs2YMaPO8/fcc48cDke9bQMtxdy5c62OAPiUqKgoHThwwOoY8JJ33nlHQ4cO1Zw5c9zPjRs3Trm5uYqKipIknThxQgEBAWrfvr1Onz6t7du367e//a2p7VdXVysvL0/jxo1r8PWysjJdeumlqqqq0po1axQaGiqptnCWlZVJqr2a/4orrtD69et1++23yzAMHThwQL169bqQoXtUo8Wx0kszjk2VOcMw6j13tpNT33//fV133XV1DlMvXbpUoaGh+vbbbzVx4kRFREQoOjr6gnMDAICWKScnp14JHDx4sN566y29+uqr+u///m8VFRUpMzNTLpdLhmFoyJAhGjRoUKPbPXOOY1VVlfr373/Wc2MffvhhDR8+XJdffrl69uzpLosJCQmaMWOG3nzzTf35z3/Wc889p1mzZmn+/Pmqrq5WQkJCSyqO3plxbEpYWJgKCwvdj51Op3ttrZ/KyclRYmJinefOtPguXbooLi5OeXl5FEcAAHzYm2++We+5u+66q87jXr16adWqVaa3+cwzz5z1tc2bN9d5PGbMGI0ZM6be+xpaGui1114znaG5NbqOY6XL3yt/mtK7d28dOXJEx44dU2VlpXJychQbG1vvfadOndJHH32kW2+91f1ceXm5SktL3X//8MMP1aNHj3P93wUAAAA/YcsZx4CAAM2cOVOTJk2Sy+VSWlqaevTo4b6kffTo0ZJqV3+/8cYb3WsmSdK3336ryZMnS6q9OjspKUkDBw5s/kEAAIBWYfbs2dq7d2+d5+666y6lpaVZlMg6jRbHKhOzg94SExNT70q2M4XxjNTU1DrrNUlSeHi4Vq9e7fV8AADANzz22GNWR7CNxoujRTOOAAAAsB/bzjgCAADAXppYx7HRa2cAAADgQxovji6KIwAAAGpRHAEAAGBKo8XRxaFqAAAA/J9Gi2MNM44AAAD4PxRHAAAAmNJEcXQ0Vw4AAADYXKNTiobL4ZU/gCdt27bN6ghe1ZrH15rH1tq15p9dax6b1PrHB+9qdMZRNZQ82F9hYaHVEbyqNY+vNY+ttWvNP7vWPDap9Y8P3tVocWR2EAAAAGc0eqja4XJ45Y8ZW7duVXx8vOLi4rRgwYJ6r+/atUvXX3+9UlJSlJKSopdeesn0ZwEAAHDuGj9UbdGMo8vl0pw5c7Ro0SKFhoZq2LBhio2NVffu3eu8LyoqSq+++up5fRYAAADnxpYzjnl5eeratavCw8MVGBioxMREbdq0ydSALuSzAAAAOLvGi2ONd/40xel0KiwszP04NDRUTqez3vv27dunO+64Q5MmTdLnn39+Tp8FAADAubHkUPWyZcu0bNky9+ORI0dq5MiR7seGYdT7jMNRN0tkZKQ2b96soKAgbdmyRZMnT9a7775r6rMAAAA4d40WR4fLOzv9aVH8qbCwsDrLBTidToWEhNR5T3BwsPvvMTExmj17tk6cOGHqswAAADh3tjzHsXfv3jpy5IiOHTumyspK5eTkKDY2ts57vvnmG/fsYl5enmpqatSpUydTnwUAAMC5a3TG0c9LM45NCQgI0MyZMzVp0iS5XC6lpaWpR48eWrp0qSRp9OjReuedd7R06VL5+/vrZz/7mebOnSuHw3HWzwIAAODCWHKo2oyYmBjFxMTUeW706NHuv48bN07jxo0z/VkAAABcmMYvjql/nQkAAAB8lG1nHAEAAGAvtjzHES3TtGnT9MEHH6hLly5au3at1XE86vjx45o6daqKi4vl5+enESNGaMKECVbH8piKigqNHTtWlZWVcrlcio+PV3p6utWxPOrMOc+hoaH17jjVkvG9a7n43qElauKqau/8QeuUmpqqhQsXWh3DK/z9/ZWZman169dr2bJl+p//+R998cUXVsfymMDAQC1evFirV6/WqlWrtG3bNu3bt8/qWB61ZMkSdevWzeoYHsf3ruXie2etF198Ua+99pok6b/+67+0fft2y7Lk5+dry5YtF7SNkpIS/fWvfz2nz/zwww+69957NWTIECUmJur5559v8jMUR3hMdHS0OnToYHUMrwgJCVFkZKSk2jVEIyIiWtUdiRwOh4KCgiRJ1dXVqq6ublUL5xcWFuqDDz7QsGHDrI7icXzvWi6+d/bx8MMPa8CAAZbt32xxrK6uPutrJSUl7tVnzsXdd9+tDRs26O2339bevXubzEFxBM5RQUGB8vPz1adPH6ujeJTL5VJKSooGDBigAQMGtKrxPfXUU/rDH/4gP79G/8mDjfG9a3ns+L2bP3++4uPj9Zvf/EaHDx92P5+ZmakNGzZIkp5//nklJCQoOTlZ//Ef/yFJKi4u1uTJk3XHHXfojjvu0N69eyVJixYtUlJSkpKSkvTGG29Iqv1dTUpKcm/7tdde04svvihJGj9+vJ577jkNGzZM8fHx2rNnjyorK/XnP/9Z69atU0pKitatW1cn88qVK5Wenq77779fd999t8rKyjRhwgTdeeedSk5O1saNGyVJ//mf/6mjR48qJSXFnXvhwoVKS0tTcnKy/vznP9f736Nt27b69a9/Lal2Bvzqq69u8v85a/ziGBP3lQZ8SVlZmdLT0zV9+vQ6dy9qDfz9/ZWdna2SkhJNnjxZBw8eVM+ePa2OdcHef/99de7cWddcc4127dpldRycB753LY9V37uTJ08qNTXV/fjHd6rbv3+/1q1bp1WrVsnlcunOO+90z2if8d133+m9997Thg0b5HA4VFJSIkl64oknFB0drXnz5snlcqm8vFz79+/XypUr9fe//12GYWjEiBG64YYb1L59+0YzulwurVixQlu2bNFLL72kN954Q+np6dq/f79mzpzZ4Gf27dun1atXq2PHjqqurta8efMUHBysEydOaOTIkbr11lv1u9/9Tp9//rmys7MlSf/4xz/05ZdfasWKFTIMQw888IA++ugjRUdHN7iPkpISvf/++02eR8xV1YBJVVVVSk9PV3JysgYPHmx1HK9p3769+vXrp23btrWK/4Dt3btXmzdv1tatW1VRUaHS0lL9/ve/N3UuD6zH965lsup716lTJ61cubLB1/bs2aPbbrtNbdu2laQG7yoXHBysiy66SFlZWbrlllt0yy23SJJ27typZ599VlJt2b/44ouVm5ur2267Te3atZMkxcXFac+ePU3erS4uLk6SFBkZqa+++srUuG688UZ17NhRkmQYhubOnauPPvpIfn5+cjqdKi4urveZDz/8UB9++KGGDh0qSSovL9eRI0caLI7V1dXKyMjQ+PHjFR4e3mgWrqoGTDAMQ1lZWYqIiNDEiROtjuNxJ06cUEBAgNq3b6/Tp09r+/bt+u1vf2t1LI/43e9+p9/97neSpF27dun111+nNLYQfO9aLrt+75o6hzQgIEArVqzQjh07lJOTo7/85S9asmRJg+89c9vjhrZRU/OvQ7YVFRV1Xg8MDJQk+fn5yeUyV7TOlF1JWrNmjU6cOKGVK1eqTZs2io2NrbePM/nuvfdejRo1qsntz5gxQ1dddZV+85vfNPleznGEx2RkZGjUqFE6fPiwBg4cqOXLl1sdyWNyc3OVnZ2tnTt3KiUlRSkpKRd8BZydFBUV6a677lJycrKGDRumAQMGaNCgQVbHggl871ouvnfNKzo6Wu+9955Onz6t0tJSvf/++/XeU1ZWplOnTikmJkbTp0/XZ599Jknq37+//ud//kdS7aHm0tJSRUdHa+PGjfrhhx9UXl6ujRs3KioqSl26dNG3336rkydPqrKyUh988EGT2YKCglRWVmZqHKdOnVKXLl3Upk0b7dy50z1r+dNt3HTTTXrrrbfczzmdTn377bf1tvfCCy+otLRU06dPN7V/DlXDY+bOnWt1BK+JiorSgQMHrI7hNb169dKqVausjuF1/fr1U79+/ayO4VF871ouvnfNKzIyUgkJCUpJSdHll1+u66+/vt57ysrK9OCDD7pn8KZNmyZJysrK0owZM/TWW2/Jz89Ps2bN0q9+9SulpqZq+PDhkqRhw4bp6quvliRNnjxZI0aM0BVXXKGIiIgms/Xr108LFixQSkqK7rvvPiUkJJz1vcnJyXrggQeUmpqqX/7yl+7td+rUSdddd52SkpJ0880369FHH9WhQ4fcM47t2rXTc889py5duri3VVhYqFdeeUURERG68847JdXe0vnMmBriMM421yop+m7v/IP00esZXtkuzq5///7asWOH1TG8Yvny5Y3+krd0rXl8rXlss2fP1mOPPWZ1DK9pzT+71jw2qXWPLzU19aznOMIzmHEEAACAKba9OGbr1q168sknVVNTo+HDh+vee++t8/rq1av13//935Jqj+vPmjVLvXr1klR7pVRQUJD8/Pzk7+/P//cBAADgAU3MOJ71KLZXuVwuzZkzR4sWLVJoaKiGDRum2NhYde/e3f2eK664Qn/5y1/UoUMHbdmyRTNmzKhzUvjixYvVuXNnK+IDAAC0So3POJ79zjZelZeXp65du7rXEkpMTNSmTZvqFMfrrrvO/fe+ffuqsLCw2XMCAAD4EktmHJctW6Zly5a5H/94ZXep9pLxsLAw9+PQ0FDl5eWddXsrVqzQwIED6zx3zz33yOFw1Ns2AAAAzk8T5zh6pzg2VeYautD7bIt27ty5UytWrHCvryRJS5cuVWhoqL799ltNnDhRERERZ73FDgAAAMxpfAHwasMrf5oSFhZW59Cz0+lUSEhIvfd99tln+uMf/6iXX35ZnTp1cj8fGhoqSerSpYvi4uIana0EAACAOU3cOcbwyp+m9O7dW0eOHNGxY8dUWVmpnJycevd+/PrrrzVlyhQ9++yz+sUvfuF+vry8XKWlpe6/f/jhh+rRo8f5/G8DAACAH7HkUHVTAgICNHPmTE2aNEkul0tpaWnq0aOHli5dKkkaPXq05s2bp++++06zZ8+WJPeyO99++60mT54sqfbq7KSkpHrnPwIAAODcNX5xjInDyt4SExOjmJiYOs+NHj3a/fcnn3xSTz75ZL3PhYeHa/Xq1V7PBwAA4GuauKq6prlyAAAAwOZsO+MIAAAAe2miODLjiH+pqan9ffDza/Saqmbflqd4KlNrHpunt+Up/OyabzuexO9l827Hk1r7zw5n18ShagtvVg3bKS4ulqQGl0ayclue4qlMrXlsnt6Wp/Cza77teBK/l827HU9q7T87nB0zjgAAADCl0eKoGoojAAAAajHjCAAAAFMan3Gs5hxHAAAA1GqiOFY3UwwAAADYHTOOAAAAMIUZRwAAAJjCjCMAAABMabQ4Gsw4AgAA4P80en8fo6rKK3/M2Lp1q+Lj4xUXF6cFCxbUz2YYeuKJJxQXF6fk5GR98sknpj8LAACAc2fLcxxdLpfmzJmjRYsWKTQ0VMOGDVNsbKy6d+/ufs/WrVt15MgRvfvuu/rnP/+pWbNmafny5aY+CwAAgHPXaHGsqbKmOObl5alr164KDw+XJCUmJmrTpk11yt+mTZs0dOhQORwO9e3bVyUlJSoqKtJXX33V5GcBAABw7hotju+5lnllp8uWLdOyZf/a9siRIzVy5Ej3Y6fTqbCwMPfj0NBQ5eXl1dnGT98TFhYmp9Np6rMAAAA4d42e4+gtI0eO1MqVK91/flwapdrzF3/K4XCYeo+Zz6IuT50TOm3aNPXv319JSUkXnOn48eMaP368br/9diUmJmrx4sXnvS27jY+xmdeax9eaxya17vExtqbZ9b8H8ADDhvbu3Wvcfffd7sevvPKK8corr9R5z4wZM4w1a9a4Hw8ePNhwOp2mPuuLfv3rXzf4fHV1tXHrrbcaR48eNSoqKozk5GTj888/b/C9TqfTcDqdZ93H7t27jf379xuJiYlN5mlqW06n09i/f79hGIZx6tQpY/DgwWfN9fe///2s27FifJ4cm2GcfXx2/Nl5amyG0fJ/drNmzTrrdlr62AzDMz+7pjIZhjXja82/l4bRsv5NOfO62fHdeeedTe4PF8aSGcem9O7dW0eOHNGxY8dUWVmpnJwcxcbG1nlPbGysVq1aJcMwtG/fPl188cUKCQkx9Vn8y4/PJw0MDHSfE3o+oqOj1aFDB4/kCgkJUWRkpCQpODhYERERcjqd57wdO46PsZnTmsfXmscmte7xMTZz7PjfgzPee+89/du//ZsOHTp01ve4XC4NHTpU9913X6PbyszMVGxsrFJSUjRkyBC99NJL552rpbBlcQwICNDMmTM1adIkJSQk6Pbbb1ePHj20dOlSLV26VJIUExOj8PBwxcXFacaMGXrsscca/Swa1tA5oRfyhfSGgoIC5efnq0+fPuf8WbuPj7GdXWseX2sem9S6x8fYrHWhv5uStHbtWl1//fVat27dWd+zZMkSdevWzdT2pk6dquzsbGVnZ+vtt9/WsWPHzjtbS9D4cjwWiomJUUxMTJ3nRo8e7f67w+Fwl0Uzn0XDDJufE1pWVqb09HRNnz5dwcHB5/x5O4+PsTWuNY+vNY9Nat3jY2zWMTO+kydPKjU11f34pxfflpWVae/evVqyZIkeeOABTZkypd42CgsL9cEHH+j+++/XG2+8YTpfRUWFJKldu3aSao+MJiUladeuXaqqqtLjjz+uuXPn6ssvv9Q999yj0aNHq6ysTA8++KBKSkpUXV2thx9+WLfddpvy8vKUlZWlFStWyOVyafjw4XrhhRfUs2dP03m8xbbFEc0jLCxMhYWF7sdOp1MhISEWJvqXqqoqpaenKzk5WYMHDz6vbdh1fIytaa15fK15bFLrHh9js4bZ8XXq1EkrV6486+sbN27UzTffrF/84hfq2LGjPvnkE/dh8DOeeuop/eEPf1BZWZmpbM8++6zmz5+vo0ePavz48erSpYv7tbCwMC1btkxPPfWUMjMztXTpUlVWVioxMVGjR4/WRRddpHnz5ik4OFgnTpzQyJEjdeutt+raa69VbGys/vSnP+n06dO64447bFEaJZseqkbzses5oYZhKCsrSxEREZo4ceJ5b8eO42Ns5rTm8bXmsUmte3yMrfl58nczJydHiYmJkqSEhAStXbu2zuvvv/++OnfurGuuucb0Ns8cqv7HP/6hHTt2aO/eve7Xbr31VklSz5491adPHwUHB6tz58666KKLVFJSIsMwNHfuXCUnJ2vixIlyOp0qLi6WJE2ePFkffvih9u/fr0mTJl3QuD2JGUcf9+NzQl0ul9LS0s77nNCMjAzt3r1bJ0+e1MCBAzVlyhQNHz78vLaVm5ur7Oxs9ezZUykpKe7tn+spCHYcH2MzpzWPrzWPTWrd42Ns5tjxvwcnT57Uzp079fnnn8vhcMjlcsnhcGjq1KnuQ/J79+7V5s2btXXrVlVUVKi0tFS///3v9fzzzze5/aCgIN1www3Kzc3VddddJ0lq06aNJMnPz0+BgYHu9/r5+am6ulpr1qzRiRMntHLlSrVp00axsbHuQ97ff/+9ysvLVV1drYqKCvchcMs192XcsMbZluM5F2aWzrBiW40tnXEuPJXJk2MzDM+Mj59d827HMBpfjudc2HFshsHvpRn87Jp/W40tx7N06VJjxowZdZ4bO3as8dFHHzX4/p07dxr33ntvo/t79NFHjfXr1xuGYRhVVVXGuHHjjA0bNhiGYRiDBg0yvv32W8MwDOOtt94yZs+e7f7cmdfeeOMNY86cOYZhGMaOHTuMnj17GseOHTMMwzDuu+8+Y/Xq1cbLL79c57NW41A1AABo9XJycnTbbbfVeW7w4MF666239Nvf/va8t/vss88qJSXFfR7iuZxjmpycrP379ys1NVVr1qxRRESEJGnVqlUKCAhQcnKy7r33Xv3v//6vduzYcd4ZPYlD1QAAoNV788036z131113nfX9/fr1U79+/Rrd5jPPPHPW1zZv3uz+e2pqap2rvX/82o9vwXzGFVdcoaFDh0qS/P39tXz58kZzNCdmHAEAAGAKM44AAACNmD17dp2rpaXa2cq0tDSLElmH4ggAANCIs91wxBdxqBoAAACmUBwBAABgCsURAAAAplAcAQAAYArFEQAAAKZQHAEAAGAKxREAAACmUBwBAABgisMwDMPqEAAAALA/ZhwBAABgSqO3HLznnnv06aefNlcWeMHVV1+t1157zeoYAACgFeBQNQAAAEzhUDUAAABMoTgCAADAFIojAAAATKE4AgAAwBSKIwAAAEyhOAIAAMAUiqONTJs2Tf3791dSUpLVUQAAAOqhONpIamqqFi5caHUMAACABlEcbSQ6OlodOnSwOgYAAECDKI4AAAAwheIIAAAAUyiOAAAAMIXiCAAAAFMojjaSkZGhUaNG6fDhwxo4cKCWL19udSQAAAA3h2EYhtUhAAAAYH/MOAIAAMAUiiMAAABMoTgCAADAFIojAAAATKE4AgAAwBSKIwAAAEwJsDpAa1BTU6Pi4mKrYzQoJCTE6ggAAKCVoDgCsMxHG/bp1d8vvuDt/LxbmOZkP+qBRJ416Zp/v+Bt2HVsAHwTxdED/Pz8mNkDzkN5Sbm+/LTA6hhe05rHBsA3cY4jAAAATKE4AgAAwBSKIwAAAEyhOAIAAMAUiiMAAABMoTgCAADAFJ8tjlu3blV8fLzi4uK0YMECq+NIko4fP67x48fr9ttvV2JiohYvvvD17QAAADzFJ9dxdLlcmjNnjhYtWqTQ0FANGzZMsbGx6t69u6W5/P39lZmZqcjISJWWliotLU033nij5bkAAAAkH51xzMvLU9euXRUeHq7AwEAlJiZq06ZNVsdSSEiIIiMjJUnBwcGKiIiQ0+m0OBUAAEAtnyyOTqdTYWFh7sehoaG2K2gFBQXKz89Xnz59rI4CAAAgyUeLo2EY9Z5zOBwWJGlYWVmZ0tPTNX36dAUHB1sdBwAAQJKPFsewsDAVFha6HzudTtvca7qqqkrp6elKTk7W4MGDrY4DAADg5pPFsXfv3jpy5IiOHTumyspK5eTkKDY21upYMgxDWVlZioiI0MSJE62OAwAAUIdPXlUdEBCgmTNnatKkSXK5XEpLS1OPHj2sjqXc3FxlZ2erZ8+eSklJkSRlZGQoJibG4mQAAAA+WhwlKSYmxnaFLCoqSgcOHLA6BgAAQIN88lA1AAAAzh3FEQAAAKZQHAEAAGAKxREAAACmUBwBAABgCsURAAAApvjscjyeVFNTo+LiYqtjNMgud8QBGtKufTt1vfqKC97Oz7uFNf0mC7TmsQHwTRRHHzHpmn+/4G38vFuY5mQ/6oE0QC3HRYHy79Llgrfj17GDB9J43sL9L1gdAajHqNgm49TTF7YR/yvl1+kVzwRCi0Jx9AA/Pz/bz+x9+WmB1RGAespPndbRg8etjgH4lppTUvUXVqdAC8U5jgAAADCF4ggAAABTKI4AAAAwheIIAAAAUyiOAAAAMIXiCAAAAFNYjsdGKioqNHbsWFVWVsrlcik+Pl7p6elWxwIAAJBEcbSVwMBALV68WEFBQaqqqtKYMWM0cOBA9e3b1+poAAAAHKq2E4fDoaCgIElSdXW1qqur5XA4LE4FAABQi+JoMy6XSykpKRowYIAGDBigPn36WB0JAABAEsXRdvz9/ZWdna0tW7YoLy9PBw8etDoSAACAJIqjbbVv3179+vXTtm3brI4CAAAgieJoKydOnFBJSYkk6fTp09q+fbsiIiIsTgUAAFCLq6ptpKioSJmZmXK5XDIMQ0OGDNGgQYOsjgUAACCJ4mgrvXr10qpVq6yOAQAA0CAOVQMAAMAUiiMAAABMoTgCAADAFK8Xx61btyo+Pl5xcXFasGCBt3cHAAAAL/FqcXS5XJozZ44WLlyonJwcrV27Vl988YU3dwkAAAAv8WpxzMvLU9euXRUeHq7AwEAlJiZq06ZN3twlAAAAvMSrxdHpdCosLMz9ODQ0VE6n05u7BAAAgJd4dR1HwzDqPedwOC54u9u2bVNhYeEFb8cXDB8+XJL0Xs1yi5MA9Q284zoNvOM6q2MAPsXRNkGOtglWx0AL5dXiGBYWVqfgOZ1OhYSEXPB2b7755gveBgAAAM6NVw9V9+7dW0eOHNGxY8dUWVmpnJwcxcbGenOXAAAA8BKvzjgGBARo5syZmjRpklwul9LS0tSjRw9v7hIAAABe4jAaOhERAAAA+AnuHAMAAABTKI4AAAAwheIIAAAAUyiONjJt2jT1799fSUlJVkcBAACoh+JoI6mpqVq4cKHVMQAAABpEcbSR6OhodejQweoYAAAADaI4AgAAwBSKIwAAAEyhOAIAAMAUiiMAAABMoTjaSEZGhkaNGqXDhw9r4MCBWr58udWRAAAA3LhXNQAAAExhxhEAAACmUBwBAABgCsURAAAAplAcAQAAYArFEQAAAKZQHAEAAGBKgNUBWoOamhoVFxdbHaNBISEhVkcAAACtBDOOAAAAMIUFwAEAAGAKM44AAAAwheIIAAAAUyiOAAAAMIXiCAAAAFMojgAAADCF4ggAAABTfHIB8OPHj2vq1KkqLi6Wn5+fRowYoQkTJlgdy7a5AAAAJB9dx7GoqEjffPONIiMjVVpaqrS0NM2bN0/du3cnFwAAwFn45KHqkJAQRUZGSpKCg4MVEREhp9NpcSr75gIAAJB8tDj+WEFBgfLz89WnTx+ro9Rh11wAAMB3+XRxLCsrU3p6uqZPn67g4GCr47jZNRcAAPBtPlscq6qqlJ6eruTkZA0ePNjqOG52zQUAAOCTxdEwDGVlZSkiIkITJ060Oo6bXXMBAABIPnpV9Z49ezR27Fj17NlTfn613TkjI0MxMTHkAgAAOAufLI4AAAA4dz55qBoAAADnjuIIAAAAUyiOAAAAMIXiCAAAAFMojgAAADCF4ggAAABTAqwO0BrU1NSouLjY6hgNCgkJsToCAABoJZhxBAAAgCksAA4AAABTmHEEAACAKRRHAAAAmEJxBAAAgCkURwAAAJhCcQQAAIApFEcAAACYwgLgNlJRUaGxY8eqsrJSLpdL8fHxSk9PtzoWAACAJNZxtBXDMFReXq6goCBVVVVpzJgxysrKUt++fa2OBgAAwKFqO3E4HAoKCpIkVVdXq7q6Wg6Hw+JUAAAAtSiONuNyuZSSkqIBAwZowIAB6tOnj9WRAAAAJFEcbcff31/Z2dnasmWL8vLydPDgQasjAQAASKI42lb79u3Vr18/bdu2zeooAAAAkiiOtnLixAmVlJRIkk6fPq3t27crIiLC4lQAAAC1WI7HRoqKipSZmSmXyyXDMDRkyBANGjTI6lgAAACSWI4HAAAAJnGoGgAAAKZQHAEAAGAKxREAAACmUBwBAABgCsURAAAAplAcAQAAYArFEQAAAKY0uQD47NmzmyMHvOSxxx6zOgIAAGglWAAcAAAApnCoGgAAAKZQHAEAAGAKxREAAACmUBwBAABgCsURAAAAplAcAQAAYArF0UamTZum/v37KykpyeooAAAA9VAcbSQ1NVULFy60OgYAAECDKI42Eh0drQ4dOlgdAwAAoEEURwAAAJhCcQQAAIApFEcAAACYQnEEAACAKRRHG8nIyNCoUaN0+PBhDRw4UMuXL7c6EgAAgJvDMAzD6hAAAACwP2YcAQAAYArFEQAAAKZQHAEAAGAKxREAAACmUBwBAABgCsURAAAApgRYHaA1qKmpUXFxsdUxGhQSEmJ1BAAA0EpQHH3EpGv+/YK38fNuYZqT/agH0gC+ge8d7OijDfv06u8XX9A2+L30XRRHD/Dz87P9zN6XnxZYHQHwOXzvYEflJeX8buK8cY4jAAAATKE4AgAAwBSKIwAAAEyhOAIAAMAUiiMAAABMoTgCAADAFJ8tjlu3blV8fLzi4uK0YMECq+NIko4fP67x48fr9ttvV2JiohYvvrB1tgAAADzJJ9dxdLlcmjNnjhYtWqTQ0FANGzZMsbGx6t69u6W5/P39lZmZqcjISJWWliotLU033nij5bkAAAAkH51xzMvLU9euXRUeHq7AwEAlJiZq06ZNVsdSSEiIIiMjJUnBwcGKiIiQ0+m0OBUAAEAtnyyOTqdTYWFh7sehoaG2K2gFBQXKz89Xnz59rI4CAAAgyUeLo2EY9Z5zOBwWJGlYWVmZ0tPTNX36dAUHB1sdBwAAQJKPFsewsDAVFha6HzudTtvca7qqqkrp6elKTk7W4MGDrY4DAADg5pPFsXfv3jpy5IiOHTumyspK5eTkKDY21upYMgxDWVlZioiI0MSJE62OAwAAUIdPXlUdEBCgmTNnatKkSXK5XEpLS1OPHj2sjqXc3FxlZ2erZ8+eSklJkSRlZGQoJibG4mQAAAA+WhwlKSYmxnaFLCoqSgcOHLA6BgAAQIN88lA1AAAAzh3FEQAAAKZQHAEAAGAKxREAAACmUBwBAABgCsURAAAApvjscjyeVFNTo+LiYqtjNOjMHXG6Xn3FBW/r593Cmn4TADe+d7Cjdu3bXfDvJr+Xvovi6CMW7n/B6ghAPUbFNhmnnr7wDflfKb9Or1z4dgAfED2kr6KH9LU6BlooiqMH+Pn52eZe10CLUnNKqv7C6hRe8+WnBVZHAACP4hxHAAAAmEJxBAAAgCkURwAAAJhCcQQAAIApFEcAAACYQnEEAACAKSzHYyMVFRUaO3asKisr5XK5FB8fr/T0dKtjAQAASKI42kpgYKAWL16soKAgVVVVacyYMRo4cKD69u1rdTQAAAAOVduJw+FQUFCQJKm6ulrV1dVyOBwWpwIAAKhFcbQZl8ullJQUDRgwQAMGDFCfPn2sjgQAACCJ4mg7/v7+ys7O1pYtW5SXl6eDBw9aHQkAAEASxdG22rdvr379+mnbtm1WRwEAAJBEcbSVEydOqKSkRJJ0+vRpbd++XRERERanAgAAqMVV1TZSVFSkzMxMuVwuGYahIUOGaNCgQVbHAgAAkERxtJVevXpp1apVVscAAABoEIeqAQAAYArFEQAAAKZQHAEAAGCK14vjtGnT1L9/fyUlJXl7VwAAAPAirxfH1NRULVy40Nu7AQAAgJd5vThGR0erQ4cO3t4NAAAAvIxzHAEAAGBKi1zHcdu2bSosLLQ6RoswfPhwqyOgFfpow8cqL/nhgrcTMyJBjrYJHkhkT+/VLLc6gu156nepXfu2ih7yKw8kAtCYFlkcb775ZqsjAD7t1d8v0ZefFlzwdmJGDPBAGrRknvpd6nr1FRRHoBlwqBoAAACmeL04ZmRkaNSoUTp8+LAGDhyo5cs5dAMAANASef1Q9dy5c729CwAAADQDDlUDAADAFIojAAAATKE4AgAAwBSKo41wX28AAGBnFEcb4b7eAADAziiONsJ9vQEAgJ1RHAEAAGAKxREAAACmUBwBAABgCsURAAAAplAcbYT7egMAADvz+r2qYR739QYAAHbGjCMAAABMoTgCAADAFIojAAAATKE4AgAAwBSKIwAAAEyhOAIAAMAUluPxgJqaGhUXF1sdo0EhISFWR0Ar9PNuYVZHQCvhqd8lfieB5uEwDMOwOkRLR3FsPWam/Ie+PlR4Qdv4ebcwzcl+1EOJgNbNE9856V/F0RPbWrj/hQvexhn8m4LWhhlHD/Dz86OgtRJfHyrUl58WWB0D8Bme/s7Z7fvLvylobTjHEQAAAKZQHAEAAGAKxREAAACmUBwBAABgCsURAAAAplAcAQAAYIpPLsdz/PhxTZ06VcXFxfLz89OIESM0YcIEq2PZNhcAAIDko8XR399fmZmZioyMVGlpqdLS0nTjjTeqe/fu5AIAADgLnzxUHRISosjISElScHCwIiIi5HQ6LU5l31wAAACSjxbHHysoKFB+fr769OljdZQ67JoLAAD4Lp8ujmVlZUpPT9f06dMVHBxsdRw3u+YCAAC+zWeLY1VVldLT05WcnKzBgwdbHcfNrrkAAAB8sjgahqGsrCxFRERo4sSJVsdxs2suAAAAyUeLY25urrKzs7Vz506lpKQoJSVFW7ZssTqWbXMBAABIProcT1RUlA4cOGB1jHrsmgsAAEDy0RlHAAAAnDuKIwAAAEyhOAIAAMAUiiMAAABMoTgCAADAFIojAAAATPHJ5Xg8raamRsXFxVbHaFBISIjVEVqUn3cLs8U2AF/hqe+LXb93/JuC1sZhGIZhdYiWjuIIAAB8AcURAAAApnCOIwAAAEyhOAIAAMAUiiMAAABMoTgCAADAFIojAAAATKE4AgAAwBQWALeRiooKjR07VpWVlXK5XIqPj1d6errVsQAAACSxjqOtGIah8vJyBQUFqaqqSmPGjFFWVpb69u1rdTQAAAAOVduJw+FQUFCQJKm6ulrV1dVyOBwWpwIAAKhFcbQZl8ullJQUDRgwQAMGDFCfPn2sjgQAACCJ4mg7/v7+ys7O1pYtW5SXl6eDBw9aHQkAAEASxdG22rdvr379+mnbtm1WRwEAAJBEcbSVEydOqKSkRJJ0+vRpbd++XRERERanAgAAqMVyPDZSVFSkzMxMuVwuGYahIUOGaNCgQVbHAgAAkMRyPAAAADCJQ9UAAAAwheIIAAAAUyiOAAAAMIXiCAAAAFMojgAAADCF4ggAAABTKI4AAAAwpckFwGfPnt0cOeAljz32mNURAABAK8EC4AAAADCFQ9UAAAAwheIIAAAAUyiOAAAAMIXiCAAAAFMojgAAADCF4ggAAABTKI42Mm3aNPXv319JSUlWRwEAAKiH4mgjqampWrhwodUxAAAAGkRxtJHo6Gh16NDB6hgAAAANojgCAADAFIojAAAATKE4AgAAwBSKIwAAAEyhONpIRkaGRo0apcOHD2vgwIFavny51ZEAAADcHIZhGFaHAAAAgP0x4wgAAABTKI4AAAAwheIIAAAAUyiOAAAAMIXiCAAAAFMojgAAADAlwOoArUFNTY2Ki4utjtGgkJAQqyMAAIBWghlHAAAAmMIC4AAAADCFGUcAAACYQnEEAACAKRRHAAAAmEJxBAAAgCkURwAAAJhCcQQAAIApPlsct27dqvj4eMXFxWnBggVWx5EkHT9+XOPHj9ftt9+uxMRELV682OpIAAAAbj65jqPL5VJ8fLwWLVqk0NBQDRs2THPnzlX37t0tzVVUVKRvvvlGkZGRKi0tVVpamubNm2d5LgAAAMlHZxzz8vLUtWtXhYeHKzAwUImJidq0aZPVsRQSEqLIyEhJUnBwsCIiIuR0Oi1OBQAAUMsni6PT6VRYWJj7cWhoqO0KWkFBgfLz89WnTx+rowAAAEjy0eLY0NF5h8NhQZKGlZWVKT09XdOnT1dwcLDVcQAAACT5aHEMCwtTYWGh+7HT6VRISIiFif6lqqpK6enpSk5O1uDBg62OAwAA4OaTxbF37946cuSIjh07psrKSuXk5Cg2NtbqWDIMQ1lZWYqIiNDEiROtjgMAAFCHT15VLUlbtmzRU089JZfLpbS0ND3wwANWR9KePXs0duxY9ezZU35+tZ0+IyNDMTExFicDAADw4eIIAACAc+OTh6oBAABw7iiOAAAAMIXiCAAAAFMojgAAADCF4ggAAABTKI4AAAAwJcDqAK1BTU2NiouLrY7RILvcEQcAALR8zDgCAADAFBYABwAAgCnMOAIAAMAUiiMAAABMoTgCAADAFIojAAAATKE4AgAAwBSKIwAAAExhAXAbqaio0NixY1VZWSmXy6X4+Hilp6dbHQsAAEAS6zjaimEYKi8vV1BQkKqqqjRmzBhlZWWpb9++VkcDAADgULWdOBwOBQUFSZKqq6tVXV0th8NhcSoAAIBaFEebcblcSklJ0YABAzRgwAD16dPH6kgAAACSKI624+/vr+zsbG3ZskV5eXk6ePCg1ZEAAAAkURxtq3379urXr5+2bdtmdRQAAABJFEdbOXHihEpKSiRJp0+f1vbt2xUREWFxKgAAgFosx2MjRUVFyszMlMvlkmEYGjJkiAYNGmR1LAAAAEksxwMAAACTOFQNAAAAUyiOAAAAMIXiCAAAAFO8fnHM8ePHNXXqVBUXF8vPz08jRozQhAkTvL1bAAAAeJjXL44pKirSN998o8jISJWWliotLU3z5s1T9+7dvblbAAAAeJjXD1WHhIQoMjJSkhQcHKyIiAg5nU5v7xYAAAAe1qznOBYUFCg/P5/7LwMAALRAzbYAeFlZmdLT0zV9+nQFBwdf0La2bdumwsJCDyVr3YYPH251BJ/00YaPVV7yg0e2FTNigEe246lM7dq3lSSPbMtTYwNaOzv+mwLf1CwLgFdVVen+++/XTTfdpIkTJ3p7d4DlJl3z7/ry0wKPbOu9muUe2Y6nMnW9+gpJ8si2PDU2oLWz478p8E1eP1RtGIaysrIUERFBaQQAAGjBvF4cc3NzlZ2drZ07dyolJUUpKSnasmWLt3cLAAAAD/P6OY5RUVE6cOCAt3cDAAAAL+POMQAAADCF4ggAAABTKI4AAAAwheJoI9OmTVP//v2VlJRkdRQAAIB6KI42kpqaqoULF1odAwAAoEEURxuJjo5Whw4drI4BAADQIIojAAAATKE4AgAAwBSKIwAAAEyhOAIAAMAUiqONZGRkaNSoUTp8+LAGDhyo5cuXWx0JAADAzev3qoZ5c+fOtToCAADAWTHjCAAAAFMojgAAADCF4ggAAABTKI4AAAAwheIIAAAAUyiOAAAAMIXleDygpqZGxcXFVsdoUEhIiNURfNLPu4VZHaEeT2Wy49iA1o7vHezCYRiGYXWIlo7iCF8zM+U/9PWhwgvezsL9L3ggDVoyT/0u/bxbmOZkP+qBRAAaw4yjB/j5+VHQ4FO+PlSoLz8tsDoGWgF+l4CWhXMcAQAAYArFEQAAAKZQHAEAAGAKxREAAACmUBwBAABgCsURAAAApvjkcjzHjx/X1KlTVVxcLD8/P40YMUITJkywOpZtcwEAAEg+Whz9/f2VmZmpyMhIlZaWKi0tTTfeeKO6d+9OLgAAgLPwyUPVISEhioyMlCQFBwcrIiJCTqfT4lT2zQUAACD5aHH8sYKCAuXn56tPnz5WR6nDrrkAAIDv8uniWFZWpvT0dE2fPl3BwcFWx3Gzay4AAODbfLY4VlVVKT09XcnJyRo8eLDVcdzsmgsAAMAni6NhGMrKylJERIQmTpxodRw3u+YCAACQfLQ45ubmKjs7Wzt37lRKSopSUlK0ZcsWq2PZNhcAAIDko8vxREVF6cCBA1bHqMeuuQAAACQfnXEEAADAuaM4AgAAwBSKIwAAAEyhOAIAAMAUiiMAAABMoTgCAADAFJ9cjsfTampqVFxcbHWMBoWEhFgdAa3Qz7uFWR0BrYSnfpf4nQSah8MwDMPqEC0dxREAAPgCiiMAAABM4RxHAAAAmEJxBAAAgCkURwAAAJhCcQQAAIApFEcAAACYQnEEAACAKSwAbiMVFRUaO3asKisr5XK5FB8fr/T0dKtjAQAASGIdR1sxDEPl5eUKCgpSVVWVxowZo6ysLPXt29fqaAAAAByqthOHw6GgoCBJUnV1taqrq+VwOCxOBQAAUIviaDMul0spKSkaMGCABgwYoD59+lgdCQAAQBLF0Xb8/f2VnZ2tLVu2KC8vTwcPHrQ6EgAAgCSKo221b99e/fr107Zt26yOAgAAIIniaCsnTpxQSUmJJOn06dPavn27IiIiLE4FAABQi+V4bKSoqEiZmZlyuVwyDENDhgzRoEGDrI4FAAAgieV4AAAAYBKHqgEAAGAKxREAAACmUBwBAABgCsURAAAAplAcAQAAYArFEQAAAKZQHAEAAGBKowuA/+Uvf1F5eXlzZYEXtGvXTuPGjbM6BgAAaAVYABwAAACmcKgaAAAAplAcAQAAYArFEQAAAKZQHAEAAGAKxREAAACmUBwBAABgis8WR9anBAAAODc+Vxz37t2rhIQEJSQkSJI+++wzzZo1y9pQAAAALUCjd445X5988kmjr0dGRnpjt6Y8/fTTeu211/TAAw9Iknr16qU9e/ZYlueMw4cPa9asWfr222+1du1affbZZ9q8ebMefPBBq6MBAABI8lJxfOaZZ876msPh0JIlS7yxW9Muu+yyOo/9/KyfeJ0xY4amTp2qmTNnSqottL///e8pjgAAwDa8UhzffPNNb2zWIy677DLt3btXDodDlZWVevPNN9WtWzerY+mHH37QtddeW+c5f39/i9IAAADU55XiuGPHDvXv31/vvvtug68PHjzYG7s1ZdasWXryySfldDo1cOBA3XTTTe5ZPit16tRJR48elcPhkCRt2LBBl156qcWpAAAA/sVhGIbh6Y3++c9/Vnp6uqZNm9bg608//bSnd9niHTt2TDNmzNDHH3+s9u3b64orrtDzzz+vyy+/3OpoAAAAkrxUHO3s2LFjevLJJ7Vv3z45HA717dtX06dPV3h4uOW5wsPDVV5erpqaGgUHB7ufAwAAsAOvF8cPPvhAn3/+uSoqKtzPPfTQQ97cZaNGjBihMWPGKCkpSZKUk5Ojv/zlL1q+fLllmSTpzjvv1Ntvv13nudTUVK1cudKiRAAAAHV55RzHM2bOnKnTp09r165dGj58uN555x317t3bm7tskmEYGjp0qPtxSkqK/vrXv1qW59ChQ/riiy906tSpOueElpaW1inbAAAAVvNqcfz444+1Zs0aJScn66GHHtLEiRM1ZcoUb+6ySf369dOCBQuUkJAgh8OhdevWKSYmRt99950kqWPHjs2a5/Dhw/rggw906tQpvf/+++7ng4KC9PjjjzdrFgAAgMZ4tThedNFFkqS2bdvK6XSqU6dOKigo8OYum7Ru3TpJ0t/+9rc6z7/11ltyOBzatGlTs+a57bbbdNttt+njjz/Wr371q2bdNwAAwLnwanEcNGiQSkpKdM899yg1NVUOh0PDhw/35i6btHnzZkv3fzZXX321/vrXv9Y7H5Qr0AEAgF145eKY9evX6/bbb69zVXBlZaUqKip08cUXe3p35+zgwYP64osvVFlZ6X7ux+c9WiE9PV0RERFau3atJk+erDVr1igiIkJ//OMfLc0FAABwhlfutbdgwQJJtWXojMDAQFuUxpdeekmPP/64nnjiCe3atUvPPfecLWYhjx49qkceeURt27bVnXfeqVdffVUHDx60OhYAAICbVw5Vd+zYUePHj1dBQYHuv//+eq+/8sor3titKe+8846ys7M1dOhQPf300youLrbFrF5AQO2Pon379jp48KAuueQSffXVVxanAgAA+BevFMdXX31Vn376qaZOnaq7777bG7s4bxdddJH8/PwUEBCg0tJSdenSRceOHbM6lkaOHKnvv/9ejzzyiB544AGVl5fr4YcftjoWAACAm1eKY2BgoPr27au//e1v6ty5s0pLSyVJwcHB3tjdObnmmmtUUlKi4cOHKzU1Ve3atdO1115raaaamhoFBQWpQ4cOio6ObvYruwEAAMzw6p1j/vd//1fTp09XWVmZDMPQxRdfrKeeekrXXHONt3Z5TgoKClRaWqpevXpZHUVjx461dCFyAACApni1OCYnJ+uxxx5TVFSUJGnPnj2aPXu21qxZ461dmuJ0OvXVV1/J5XK5n4uOjrYwkTRv3jz97Gc/U0JCgtq2bet+vrkXJAcAADgbr67jGBQU5C6NkhQVFaWgoCBv7rJJzz33nNavX69u3brJ39/f/bzVxfGtt96SpDqzjlYsSA4AAHA2Xp1xfOqpp3T69GklJia6b+/XoUMHDR48WJIUGRnprV2fVXx8vNasWaPAwMBm3zcAAEBL5tUZx/z8fEm1ayf+2N69e+VwOLRkyRJv7r5B4eHhqqqqslVx/Oqrr9S2bVt17txZ+/btU25urrp27arbbrvN6mgAAABuXp1xbMrbb7+tO++8s1n29fjjj8vhcMjpdOqzzz5T//7965RHq9ZynDdvnt5++205HA4lJCRox44duuGGG/TPf/5TvXr1UlZWliW5AAAAfsqrM45NWbJkSbMVxzNXckdGRio2NrZZ9mlGTk6O1q1bp9OnT+uWW27Rhx9+qLZt26q6utry2yACAAD8mKXFsTknOxsqqN9//72OHz9u6XI8F110kQIDAxUYGKgrr7zSfUV1QECA2rRpY1kuAACAn7K0ODocjmbf5/jx4zV//nz3jF7nzp0VHR2tadOmNXsWSSopKdG7774rwzBUWlqqd999V1JtqT516pQlmQAAABriMzOOZ5w6dUrBwcFavny5UlNTlZ6eruTk5GbPccYNN9yg999/X1LtkkBn/n7mMQAAgF1YWhyvu+66Zt+ny+VSUVGR1q9fr0ceeaTZ9/9TTz/9tKn3NeeFRAAAAA3xa46d7NmzR4sWLdI//vGPOs/PnDmzOXZfx4MPPqh77rlHV155pa699lodO3ZMV111VbPnOFdWLF0EAADwY15ZjmfYsGFasWKFJOnvf/+7/vrXvyouLk7/+Mc/FBsbq3vvvdfTu2z1hg4dqlWrVlkdAwAA+DCvzDhWV1e7/75s2TItWrRIDz30kF5//XXL71PdUllxIREAAMCPeeUcx5qaGn3//feqqamRYRjq3LmzJKldu3Z17g8N8yxcpx0AAECSl4pjaWmpUlNTZRiGHA6HvvnmG1166aUqKyujAJ0nKy4kAgAA+LFmveXgDz/8oOLiYoWHhzfXLuspLi7W3LlzVVRUpIULF+qLL77Qxx9/rOHDh1uW6dChQyoqKtK1116roKAg9/Nbt27VwIEDLcsFAADwY81yVfUZbdu2tbQ0SlJmZqZuuukmFRUVSZKuuuoqS69YXrJkiR588EG9+eabSk5O1saNG92vvfDCC5blAgAA+KlmLY6SdN999zX3Lus4efKkEhIS5OdXO/SAgAD3362wfPlyrVy5Ui+//LKWLFmil19+WYsXL5bEeY0AAMBemnUB8NzcXPeFMlZp166dTp486b5Ked++fbr44osty+NyudyHp6+44gq9+eabSk9P19dff01xBAAAtuL14pifn681a9Zow4YNuvzyyxUfH+/tXTbq0Ucf1QMPPKCjR49q1KhROnnypP7rv/7LsjyXXHKJ8vPz9ctf/lKSFBQUpFdffVXTp0/XwYMHLcsFAADwU165OObw4cPKyclRTk6OOnbsqISEBL3++ut17sNsperqah0+fFiGYegXv/iF2rRpY1mWwsJC+fv769JLL633Wm5urq6//noLUgEAANTnleLYq1cvRUVF6cknn1TXrl0lSbfeeqs2bdrk6V2dszvuuEMJCQlKSEjQlVdeaXUcAACAFsMrV4W8+OKLuuSSS3TXXXfpj3/8o3bs2GGb8/Xmz58vf39/PfLII0pLS9Nrr72mr7/+2upYDbL6QiIAAIAf8+o6juXl5dq4caNycnK0c+dODR06VHFxcbrpppu8tctzcuTIEb388stas2aN8vPzrY5TR25urlasWKGnn37a6igAAACSmnEB8O+++04bNmzQunXrLF03UZIKCgq0fv16rV+/Xn5+fkpISNDdd99taSap4QuJxo0bZ3UsAAAASc185xg7GD58uKqrqzVkyBAlJCRYviC53S8kAgAAOMPniuOhQ4fUrVs3q2O42flCIgAAgB9r1gXA7aBbt2764IMP9Pnnn6uiosL9/EMPPWRJnhdffFE5OTm66667dPPNNysxMdE2FxIBAAD8mM/NOM6cOVOnT5/Wrl27NHz4cL3zzjvq3bu3nnrqKUtz2f1CIgAAAJ8rjsnJyVqzZo37/5aVlWnKlCl6/fXXrY7mZqcLiQAAAM7wyjqOdvazn/1MktS2bVs5nU61adNGBQUFFqeqq2PHjho1ahSlEQAA2IrPneN4yy23qKSkRPfcc49SU1PlcDg0fPhwq2MBAADYns8dqv6xyspKVVRU6OKLL7Y6CgAAgO353IzjmDFjFB0dreuvv17XXXcdpREAAMAkn5txPHbsmHJzc7Vnzx7985//VJs2bRQVFaXp06dbHQ0AAMDWfG7GMTw8XBdddJHatGmjNm3aaNeuXTp06JDVsQAAAGzP52Ycb7vtNnXq1ElJSUmKiorSL3/5S/n5+dzF5QAAAOfM54rj4sWLlZubq8LCQkVERCg6OlrR0dG68sorrY4GAABgaz5XHM8oKyvTypUr9frrr6uwsFD5+flWRwIAALA1nyuOzzzzjHJzc1VeXq6+ffsqKipKUVFRCg8PtzoaAACArflccVy/fr2io6N1ySWXWB0FAACgRfG54ggAAIDzw+XEAAAAMIXiCAAAAFN8ZgHw7777rtHXO3bs2Cw5AAAAWiqfOccxNjZWDodDhmHo+PHjat++vSSppKREl112mTZv3mxxQgAAAHvzmRnHM8Vw5syZuvXWWxUTEyNJ2rJli3bs2GFlNAAAgBbB585x3L9/v7s0SlJMTIx2795tYSIAAICWwWdmHM/o1KmTXn75Zd1xxx1yOBxavXq1OnXqZHUsAAAA2/OZcxzP+O677/TSSy9pz549kqSoqCg99NBDXBwDAADQBJ8rjmeUlpbK4XAoKCjI6igAAAAtgs8dqj5w4IAeffRRff/995JqD10/88wz6tmzp8XJAAAA7M3nZhxHjRqlRx55RL/+9a8lSbt27dILL7ygv/3tbxYnAwAAsDefu6q6vLzcXRolqV+/fiovL7cwEQAAQMvgc4eqw8PDNW/ePKWkpEiSVq9erSuuuMLiVAAAAPbnc4eqv//+e7344ovKzc2VYRiKiorSlClT1KFDB6ujAQAA2JrPFcczuKoaAADg3PjcoWquqgYAADg/PjfjyFXVAAAA54erqrmqGgAAwBSfO1TNVdUAAADnx+cOVXNVNQAAwPnxueIIAACA8+Mzh6rvv//+Rl9/5ZVXmikJAABAy+QzxfHuu++2OgIAAECL5jOHqidMmKDFixfrueee0x/+8Aer4wAAALQ4PjPj+M0332j37t3avHmzEhMT9dO+HBkZaVEyAACAlsFnZhw3bNigFStWKDc3V717965THB0Oh5YsWWJhOgAAAPvzmeJ4xrx58zR58mSrYwAAALQ4PlccAQAAcH587paDAAAAOD8URwAAAJjiM1dVn3HgwAH9v//3/yRJ3bp1U8+ePS1OBAAA0DL4THE8deqUHnzwQR0/flz/9m//JsMwdPDgQV122WWaP3++goODrY4IAABgaz5zccwTTzyhNm3a6A9/+IP8/GqP0NfU1Oj5559XRUWFZsyYYXFCAAAAe/OZ4piQkKDVq1crIKDuJGt1dbWSk5O1fv16i5IBAAC0DD5zcUybNm3qlUZJCggIUGBgoAWJAAAAWhafOcexoqJCn376ab1bDRqGocrKSotSAQAAtBw+UxwvvfRSPf300w2+dskllzRzGgAAgJbHZ85xBAAAwIXxmRnHd999t9HXBw8e3ExJAAAAWiafKY7vv/9+o69THAEAABrHoeqfePvtt3XnnXdaHQMAAMB2fGY5HrOWLFlidQQAAABbojj+BBOwAAAADaM4/oTD4bA6AgAAgC1RHH+CGUcAAICGURx/4rrrrrM6AgAAgC351FXVhw4d0qZNm1RUVCRJCgkJ0a233qpu3bpZnAwAAMD+fGbGccGCBcrIyJAk9e7dW71795YkZWRkaMGCBVZGAwAAaBF8ZsYxPj5ea9euVZs2beo8X1lZqaSkpCbvLAMAAODrfGbG0eFwuA9R/9g333zDldQAAAAm+MwtB6dPn67f/OY36tq1qy677DJJ0tdff62jR49qxowZFqcDAACwP585VC1JNTU1ysvLk9PplGEYCgsLU+/eveXv7291NAAAANvzqeIIAACA8+cz5zg25r777rM6AgAAgO0x4yipqKhIISEhVscAAACwNZ+fcczNzdX8+fOtjgEAAGB7PnNV9Y/l5+drzZo12rBhgy6//HINHjzY6kgAAAC25zPF8fDhw8rJyVFOTo46duyohIQEGYahN9980+poAAAALYLPFMfbb79dUVFReuWVV9S1a1dJ0htvvGFtKAAAgBbEZ85xfPHFF3XJJZforrvu0h//+Eft2LFDXBcEAABgns9dVV1eXq6NGzcqJydHO3fu1NChQxUXF6ebbrrJ6mgAAAC25nPF8ce+++47bdiwQevWrdOSJUusjgMAAGBrPl0cAQAAYJ7PnOMIAACAC0NxBAAAgCkURwAAAJhCcQQAAIApFEcAAACY8v8BikTKAN0KlbsAAAAASUVORK5CYII=\n"
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "dimensional_stacking.create_pivot_plot(x, y) # 2, nbins=3\n",
    "plt.show()"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "##### What this means for us\n",
    "Scenarios of interest for creating high(?) annual damage are scenarios with high values for:\n",
    "    A1-5 Pfail and discount rate 0\n",
    "\n",
    "This may change after running with SOBOL and more scenarios\n",
    "\n",
    "Also not entierly sure how to pull values for this since the pfail is only supposed to range between 0 and 1 and discount rate is between 1.5 and 4.5"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "#### Outcome: Expected Number of Deaths"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "##### Define x, y, and threshold"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "outputs": [
    {
     "ename": "KeyError",
     "evalue": "'Expected Number of Deaths'",
     "output_type": "error",
     "traceback": [
      "\u001B[1;31m---------------------------------------------------------------------------\u001B[0m",
      "\u001B[1;31mKeyError\u001B[0m                                  Traceback (most recent call last)",
      "\u001B[1;32m~\\AppData\\Local\\Temp/ipykernel_1216/247945744.py\u001B[0m in \u001B[0;36m<module>\u001B[1;34m\u001B[0m\n\u001B[0;32m      1\u001B[0m \u001B[0mx\u001B[0m \u001B[1;33m=\u001B[0m \u001B[0mexperiments\u001B[0m\u001B[1;33m\u001B[0m\u001B[1;33m\u001B[0m\u001B[0m\n\u001B[1;32m----> 2\u001B[1;33m \u001B[0mdata\u001B[0m \u001B[1;33m=\u001B[0m \u001B[0moutcomes\u001B[0m\u001B[1;33m[\u001B[0m\u001B[1;34m\"Expected Number of Deaths\"\u001B[0m\u001B[1;33m]\u001B[0m\u001B[1;33m\u001B[0m\u001B[1;33m\u001B[0m\u001B[0m\n\u001B[0m\u001B[0;32m      3\u001B[0m \u001B[0my\u001B[0m \u001B[1;33m=\u001B[0m \u001B[0mdata\u001B[0m \u001B[1;33m<\u001B[0m \u001B[0mnp\u001B[0m\u001B[1;33m.\u001B[0m\u001B[0mquantile\u001B[0m\u001B[1;33m(\u001B[0m\u001B[0mdata\u001B[0m\u001B[1;33m,\u001B[0m \u001B[1;36m.5\u001B[0m\u001B[1;33m)\u001B[0m \u001B[1;31m#np.percentile(data, 10) # 10 percent of worst outcomes\u001B[0m\u001B[1;33m\u001B[0m\u001B[1;33m\u001B[0m\u001B[0m\n",
      "\u001B[1;31mKeyError\u001B[0m: 'Expected Number of Deaths'"
     ]
    }
   ],
   "source": [
    "x = experiments\n",
    "data = outcomes[\"Expected Number of Deaths\"]\n",
    "y = data < np.quantile(data, .5) #np.percentile(data, 10) # 10 percent of worst outcomes"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "##### Tradeoff density and coverage"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "prim_alg = prim.Prim(x, y, threshold=0.8)\n",
    "box1 = prim_alg.find_box()\n",
    "box1.show_tradeoff()\n",
    "plt.show()"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "### Sensitivity Analysis"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "##### As a failsafe, drop NaN outcomes by converting to pandas DataFrame"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "outcomes_pd = pd.DataFrame.from_dict(outcomes)\n",
    "outcomes_pd.dropna(inplace=True)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "##### Convert outcomes back into array dict"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "outcomes_nonan = outcomes_pd.to_dict('list')\n",
    "\n",
    "for outcome in outcomes_nonan.keys():\n",
    "    outcomes_nonan[outcome] = np.array(outcomes_nonan[outcome])\n",
    "\n",
    "outcomes = outcomes_nonan"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "##### Drop corresponding runs from experiments"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "experiments.drop(list(set(experiments.index) - set(outcomes_pd.index)), inplace=True)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "### Feature Scoring"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "x = experiments.loc[:,['A.0_ID flood wave shape', 'A.1_pfail', 'A.2_pfail', 'A.3_pfail', 'A.4_pfail', 'A.5_pfail', 'A.1_Bmax', 'A.2_Bmax', 'A.3_Bmax', 'A.4_Bmax', 'A.5_Bmax',  'A.1_Brate', 'A.2_Brate', 'A.3_Brate', 'A.4_Brate', 'A.5_Brate', 'discount rate 0', 'discount rate 1', 'discount rate 2']]\n",
    "y = outcomes\n",
    "\n",
    "plt.figure(figsize = (10,7))\n",
    "\n",
    "fs = feature_scoring.get_feature_scores_all(x, y)\n",
    "sns.heatmap(fs, cmap=\"viridis\", annot=True, )\n",
    "\n",
    "plt.show()"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}